---
title: 概率与统计 II · 第 2 讲
---

# STA2002 概率与统计 II · 第 2 讲笔记
## Parameter Estimation I（参数估计 I）

> 授课：Zhenxing Guo、Ka Wai Tseng（香港中文大学（深圳）数据科学学院，2026 年 9 月）
> 教材：Hogg, Tanis & Zimmerman (2015) *Probability and Statistical Inference*, 9th ed., Pearson
> 对应教材章节：§6.1、§6.2、§6.4（讲义第 2 页明确给出 Suggested reading）
> 配套材料：`Lec2_Covid.pdf`（R 实践讲义，7 页）、`UM_C19_2021.csv`（真实数据集，1063 行）

---

## 0. 本讲地图（先说清楚这一讲在干什么）

第 1 讲做完了复习（概率论那一套：随机变量、分布、矩、极限定理）。从这一讲开始，课程正式从"概率（Probability）"翻到"统计（Statistics）"这一面。

第 1 讲笔记里已经强调过这两者的分水岭：概率是**已知模型推数据**，统计是**已知数据推模型**。本讲要解决的就是统计最核心的那件事——**我不知道总体分布的参数（比如正态的 $\mu$ 和 $\sigma^2$）是多少，我只有一堆样本，怎么把参数"猜"出来？**

讲义第 2 页列了三件事，其实就是这一讲的两条腿：

| 讲义原文 | 中文 | 在本讲的地位 |
| --- | --- | --- |
| Data visualization | 数据可视化 | 第一部分（第 1–3 节）：直方图、箱线图 |
| Explanatory data analysis | 探索性数据分析 | 第一部分（第 3–4 节）：用 UM Covid-19 真实数据走一遍 |
| Maximum likelihood estimation (MLE) | 最大似然估计 | 第二部分（第 5–8 节）：本讲的**理论核心** |

这两条腿不是拼在一起的，而是有因果关系的。第一部分你会看到：我们分析 Covid 数据时，为了预测明年阳性人数，随手用了"把去年所有阳性数加起来当 Poisson 均值 $\mu$"、"把 $\sum \text{Positive}/16000$ 当感染概率 $p$"这种做法。这两个"随手"的动作其实都是**估计**——而且是没有理论依据的、临时凑出来的估计。第二部分就给出一个**有严格理论支撑的通用配方**：极大似然估计（Maximum Likelihood Estimation, MLE）。这就是本讲从实践走向理论的主线。

**而这条主线的闭环出现在板书上**：课堂板书补了一个讲义没有的 Poisson $(\lambda)$ 例题，算出 $\hat\lambda = \bar x$；把它代回第 4 节会发现，**那两个"随手凑出来"的估计量恰好都是 MLE**（见 7.7.1 节）。也就是说，**讲义给了直觉、板书证明了直觉**——这是本讲最值得记住的一处呼应。

**本笔记的材料构成**：课件 `Lecture2 - Parameter Estimation I.pdf`（18 页）+ 配套 R 实践讲义 `Lec2_Covid.pdf`（7 页）+ 数据集 `UM_C19_2021.csv` + **本讲课堂板书**（内容已提炼并入 2.4、6.3、7.2、7.3.1、7.4.1、7.6.1、7.7、7.8 各节）+ **课堂抄录笔记**（2026-09-15 并入，落点为 1.1、5.4、7.3.1、7.6.1、7.7；抄录笔误的逐条修正见文末「课堂抄录笔记的合并」）。板书相对讲义新增了什么，见文末诚实备注。

> 一处诚实的备注：讲义第 2 页把"探索性数据分析"写成 **Explanatory** data analysis，标准术语其实是 **Exploratory** Data Analysis（EDA）。前者意为"解释性的"，后者才是统计学的"探索性的"，这里按 EDA 理解即可。（另外第 1 讲笔记里授课教师名字记为 Ka Wai **Tsang**，本讲 Slides 上写的是 Ka Wai **Tseng**，两种拼写都出现过，以学校正式名单为准。）

---

## 1. 数据可视化之一：直方图（Histogram）

### 1.1 直方图在解决什么问题

拿到一批连续型的观测值（比如 1000 个学生的身高），最原始的形态就是一串数字，人眼完全看不出结构。直方图（Histogram）做的事很朴素：**把连续取值切成若干区间（称为 bin，组/箱），然后数每个区间里落了多少个观测**，再把"个数"画成柱子。

讲义第 3 页给的两条性质值得逐字读：

- **Height（柱子的高度）**：表示该区间内数据点的**相对频数（relative frequency）或密度（density）**。
  - "相对频数"就是"落在这个区间的数据个数 ÷ 总个数"，即比例。用相对频数画图的好处是：柱高之和为 1，与样本量 $n$ 无关，换一批数据也能直接比。
  - 若用"密度"画，则柱高需要再除以组距，这样柱子的**面积**才等于比例。
- **Area（柱子的面积）**：与观测个数成正比。
  - 这句话是把直方图与后面要学的概率密度函数（PDF）对接的桥。回忆一下第 1 讲笔记里 PDF 的定义：连续情形下**概率 = 密度曲线下的面积**。直方图正是这个思想的"离散化版本"——柱子的面积对应那一段上数据的比例，形状就是经验密度曲线。**这就是为什么可以通过直方图去"看"总体分布是什么样**，也直接解释了第 8 页那句"Histogram tells us that the sample is likely drawn from a normal population $N(\mu,\sigma^2)$"。

**把上面这两条"文字描述"落成公式（课堂抄录）**

设共分 $k$ 个箱（bin），第 $j$ 个箱的**组距为 $w_j$**，落在其中的**观测个数为 $n_j$**，总样本量为 $n$。板书给了两个量：

$$
\text{bin }j\ \text{的相对频数} = \frac{n_j}{n},
\qquad
\text{bin }j\ \text{的密度} = \frac{n_j}{w_j\,n} = \frac{1}{w_j}\cdot\frac{n_j}{n}
$$

**两者只差一个 $1/w_j$**。它们的区别和用途：

| | 公式 | 柱高之和 | 柱面积之和 | 什么时候用 |
| --- | --- | --- | --- | --- |
| **相对频数** | $n_j/n$ | $=1$ | 只有**等宽**时才 $=1$ | 各组等宽、只想比较高低 |
| **密度** | $n_j/(w_j n)$ | $=\sum 1/w_j$（无意义） | **恒 $=1$** | 通用；不等宽时**必须**用它 |

**为什么密度要再除以组距？** 因为只有这样，**柱子的面积**才等于比例：

$$
\text{面积}_j = w_j \times \frac{n_j}{w_j\,n} = \frac{n_j}{n}
$$

于是板书写下了这个归一化恒等式：

$$
\sum_{j=1}^{k} w_j \cdot \frac{n_j}{w_j\,n} = \frac{1}{n}\sum_{j=1}^{k} n_j = \frac{n}{n} = 1
$$

**为什么这一个式子值得单独写一行**：

- 左边是"**所有柱子的面积之和**"，右边等于 1。这正是第 1 讲 PDF 的定义要求 $\int_{-\infty}^{\infty}f(x)\,dx = 1$ 的**离散版本**。**用密度作柱高，等价于在构造一个"合法的概率密度函数"**——这解释了为什么直方图的形状可以直接和理论 PDF 曲线叠在一起比较。
- **换成相对频数作柱高就会出问题**：那时"柱高之和 $=1$"成立，但"面积之和 $=1$"只在**所有箱子等宽**时成立。**一旦组距不等**（例如把 $[0,1)$ 和 $[1,10)$ 放在一张图上），用相对频数画图会**严重骗人**——宽箱会被视觉上低估。此时必须用密度。
- 三者关系一句话记住：**面积 = 比例 = 概率**；**柱高是相对的，面积才是绝对的**。
- 这也是为什么专业软件（R 的 `hist(freq=FALSE)`、Python `density=True`）默认画的是密度而非计数——它保证图形与理论密度曲线**可直接叠加比较**。

### 1.2 组距（bin width）的取舍——本页最重要的信息

讲义第 4 页开头一句就是重点：**"The choice of bin size (or number of bins) is important."** 组距选得对不对，直接决定你能不能从图上看出真相。

讲义给了两个方向的错误：

- **Too small（组距太小）**：Creates artificial peaks and valleys, overfitting the data。
  - 组距太小意味着每个 bin 里只有零星几个点，于是柱高剧烈起伏，图上长出一堆"假峰假谷"（artificial peaks and valleys）。这些起伏完全不是总体的真实结构，只是当前这批样本的偶然噪声被原样画了出来。讲义用的词非常准确——**overfitting（过拟合）**：模型（这里是直方图）把样本的噪声当成规律记住了。
- **Too large（组距太大）**：Hides important details and patterns in the data。
  - 组距太大，柱子数量太少，所有细节被"抹平"。极端情况下只有一个柱子，什么信息都没有。这跟"过拟合"相反，是**过度平滑（over-smoothing）**。

讲义配了一张经典的例子图：**蜂蜡熔点（melting points of beeswax）**的数据，同一批数据分别用组距 (a) 0.1、(b) 0.2、(c) 0.5 画三张直方图：

- (a) 组距 0.1（图上横轴 62.5–65.0，纵轴 Count 0–8）：柱子很细碎，能看出大概在 63.4–63.7 之间集中，但边缘有很多高低起伏的碎柱子。
- (b) 组距 0.2（纵轴 0–16）：高度大约翻倍（因为每个 bin 合并了原来两个 bin 的量），峰的轮廓清楚了一些，但仍有起伏。
- (c) 组距 0.5（纵轴 0–40）：只剩很少几根柱子，看起来是一个光滑的单峰形状，但细节（比如是否真有双峰）已经看不出来了。

这张图要说明的本质是一个**偏差–方差权衡（bias–variance tradeoff）**：组距小 → 偏差小、方差大（图很"毛"）；组距大 → 方差小、偏差大（图很"糊"）。跟第 1 讲里 CLA/极限定理那种"样本量越大越准"是不同性质的问题——这里是在**同一个固定样本**上做取舍，没有任何"免费午餐"。

讲义最后给了一个实用建议：**"Most statistical software (e.g., R, Python) can automatically select a reasonable number of bins based on some rules."** 常用的自动规则有 Sturges 规则（bin 数约为 $\log_2 n + 1$）和 Freedman–Diaconis 规则（组距约为 $2\,\mathrm{IQR}/n^{1/3}$，对偏态和离群点更稳健）。R 的 `hist()` 不指定 `breaks` 时用的就是 Sturges 规则的变体；Python 的 `matplotlib` 默认 `bins=10`，`numpy.histogram` 提供 `'auto'`（取 Sturges 与 FD 中较大者）。**考试和作业里，除非题目指定组距，一般不需要自己算，交给软件默认即可，但要能解释"调组距会怎样改变图形"。**

---

## 2. 数据可视化之二：箱线图（Boxplot）

直方图看的是"分布形状"，但在比较多组数据（比如"教职工 vs 走读学生 vs 住宿学生"）、或者想快速找离群点时，直方图不方便。箱线图（Boxplot，也叫箱须图 Box-and-Whisker Diagram）就是为这个场景设计的。

### 2.1 五数概括（Five-Number Summary）

讲义第 5 页第一句定义：箱线图是**基于五数概括、标准化地展示数据分布**的方法。五个数是：

| 记号 | 名称 | 含义 |
| --- | --- | --- |
| 最小值 | Minimum | 数据中最小的观测 |
| $Q_1$ | 第一四分位数（first quartile） | 排序后处在 25% 位置的数，即约有 25% 的数据小于它 |
| 中位数 | Median | 50% 位置，也叫第二四分位数 $Q_2$ |
| $Q_3$ | 第三四分位数（third quartile） | 75% 位置 |
| 最大值 | Maximum | 数据中最大的观测 |

这里有一个容易含糊的地方要先讲清楚：**分位数（quantile）通常不唯一。** 当 $nQ$ 不是整数时，不同软件用不同的插值方法（R 的 `quantile()` 默认是 type 7，即线性插值；`summary()` 也用它），所以同一批数据在 R 和 Python 里算出来的 $Q_1$ 可能差一点点。这不是 bug，是定义的自由度。本讲后面看到 R 输出的 380.8 这种"带小数"的四分位数，就是这个原因。

### 2.2 四分位距与内外栅栏（IQR, Inner/Outer Fence）

讲义接着给了三个定义，这是箱线图全部"魔法"的来源：

**四分位距（Interquartile Range, IQR）**：

$$
\mathrm{IQR} = Q_3 - Q_1
$$

它的含义是"中间 50% 数据所占据的宽度"。为什么不用极差（$Max - Min$）来度量波动？因为极差只看两个极端点，一个离群点就能把极差毁掉。IQR 天然规避了头部和尾部的极端值，是**稳健（robust）**的离散度度量。这个"稳健性"的思路会在后面反复出现。

**内栅栏与外栅栏（Inner / Outer Fence）**：在箱体左右各画两条"虚拟的线"：

$$
\text{下内栅栏} = Q_1 - 1.5\,\mathrm{IQR}, \qquad \text{上内栅栏} = Q_3 + 1.5\,\mathrm{IQR}
$$

$$
\text{下外栅栏} = Q_1 - 3\,\mathrm{IQR}, \qquad \text{上外栅栏} = Q_3 + 3\,\mathrm{IQR}
$$

（讲义原文的表述是"the left or right of the box at a distance of $1.5\times \mathrm{IQR}$ ($3\times \mathrm{IQR}$)"，即从箱体边缘向外延伸 $1.5\,\mathrm{IQR}$ 和 $3\,\mathrm{IQR}$ 的距离。）

注意这两个系数 $1.5$ 和 $3$ 是**约定俗成**的经验常数，不是从某个概率分布严格推导出来的。它们的直觉来自正态分布：在正态总体下，落在 $\pm 1.5\,\mathrm{IQR}$ 之外的概率大约只有千分之几，所以"跑到内栅栏外面"本身就很反常，值得被单独标记出来。$3\,\mathrm{IQR}$ 更是极端罕见。

**须（Whisker）的定义**是这一页最容易读错的一句：

> "Lower (Upper) whisker is the larger (smaller) one of lower (upper) inner fence and minimum (maximum)."

拆开看就是：

$$
\text{下须} = \max(\text{下内栅栏},\ \text{最小值}), \qquad \text{上须} = \min(\text{上内栅栏},\ \text{最大值})
$$

也就是说，**须不会真的画到栅栏那条线上，而是画到"不超过内栅栏的最极端那个真实数据点"**。如果最小值本身就在下内栅栏以内，那下须就画到最小值；如果最小值已经跑到内栅栏外面去了，下须就停在"内栅栏以内最靠外的那个数据点"。**这是箱线图的关键设计：须只表示"正常数据"的范围，落在栅栏外的点一律不画进须里，而是单独点出来。**

**两级离群点**（讲义最后两条）：

- **可疑离群点（Suspected outlier）**：落在内栅栏与外栅栏之间。也就是说它超出了 $1.5\,\mathrm{IQR}$ 但不超出 $3\,\mathrm{IQR}$。讲义图（第 5 页下半部分）里画成靠近箱体的浅色点。
- **离群点（Outlier）**：超出外栅栏，即超过 $3\,\mathrm{IQR}$。图里画成远离箱体的两个黑点。

第 5 页那张示意图值得对着读：从左到右依次是——两个黑色实心点（Outlier）→ 一条虚竖线（Outer fence，标注 $3\,\mathrm{IQR}$）→ 几个浅色点（Suspected outlier）→ 一条虚竖线（Inner fence，标注 $1.5\,\mathrm{IQR}$）→ 矩形箱体的左边缘（$Q_1$）→ 箱内的竖线（Median）→ 箱体右边缘（$Q_3$）→ 箱体右侧的横线（上须）。

> 一个必须知道的软件差异：**R 的默认 `boxplot()` 只用 $1.5\,\mathrm{IQR}$ 这一个门槛**（按 R 自己的 quartile 定义），把所有超过它的点都画成单独的点，而且不画外栅栏、不区分"可疑"和"确定"离群点。Hogg 教材这套"内外两层栅栏 + 可疑离群点"的说法是更细的版本。做作业时如果题目明确问 inner/outer fence，就按教材的算；只是画图用 `boxplot()` 的话，看到的就是 R 的单层版本。

### 2.3 怎么读箱线图（讲义第 6 页）

讲义第 6 页给了四条解读要点，逐条说：

**第一，"The box shows the middle 50% of the data."** 箱体从 $Q_1$ 到 $Q_3$，宽度是 IQR，涵盖了数据中心那 50% 的观测。箱体越窄，说明这批数据越"抱团"。

**第二，"The whiskers show the range of 'normal' data points, extending to the points within $1.5\times\mathrm{IQR}$ of the box."** 须代表"正常的"数据范围。

**第三，"The two dots beyond the outer fence are identified as outliers."** 外栅栏之外的点点就是"确定的"离群点。

**第四，也是最有信息量的一句："The distribution appears slightly left-skewed as the upper whisker is shorter than the lower one."**

这里要小心，因为直觉容易搞反。判断偏态（skewness）看的是**两条须的相对长度和箱体在须之间的位置**：

- 如果**下须比上须长**（左边拖得远），说明数据有一个**向左延伸的长尾（left tail）**，分布是**左偏（left-skewed / negatively skewed）**。
- 如果**上须比下须长**（右边拖得远），说明有**向右的长尾**，分布是**右偏（right-skewed / positively skewed）**。
- 如果两侧差不多、中位数大致在箱体中央，则大致对称。

讲义的例子是"上须比下须短"，所以是**左偏**。为什么左偏会导致左须长？因为左偏意味着左侧有一批特别小的值，它们被"挤"在 $Q_1$ 附近甚至推到栅栏外侧，于是下须不得不向左边延伸很远去够到最后一个"正常"的点；而右侧数据集中，上须很快就停住了。

讲义最后总结箱线图的三大用途：**理解数据的方差（variance）、偏度（skewness），以及识别离群点（identify outliers）**。

### 2.4 黑板补充：须的精确定义与两级离群点阈值

这一节的内容来自课堂板书，它把讲义第 5 页那句绕口的"须 = 内栅栏与最值中较大/较小的那个"**写成了严格的数学表达式**，并且把两级离群点的阈值单独列了出来。

**（1）分位数的位置**：板书在 $Q_1$ 上方标了 $1/4$、在 $Q_3$ 上方标了 $3/4$，在 $Q_2$ 下方写 "median"。也就是把五数概括按**累积比例**排成一行：

$$
\underbrace{\min}_{0},\quad \underbrace{Q_1}_{1/4},\quad \underbrace{Q_2}_{\text{median},\,1/2},\quad \underbrace{Q_3}_{3/4},\quad \underbrace{\max}_{1}
$$

这说明 $Q_1$、$Q_2$、$Q_3$ 就是**把数据按从小到大排好、在 1/4、1/2、3/4 位置切三刀**得到的三个分界值。板的左侧还画了箱线图的示意：一根竖轴（$y$ 轴）、箱体上标 $Q_1$（下沿）、$Q_2$: median（箱内横线）、$Q_3$（上沿），箱体上方一条虚线标 $Q_3 + 1.5\,\mathrm{IQR}$，下方一条虚线标对应的下内栅栏。

**（2）IQR**：板书中文写作

$$
\mathrm{IQR} = Q_3 - Q_1
$$

与讲义完全一致。

**（3）下须的精确定义（这一条是板书最有价值的部分）**：板书先写下

$$
\text{lower whisker}: \quad Q_1 - 1.5\,\mathrm{IQR}
$$

这其实是**下内栅栏的位置**。紧接着板书给出了真正的"须画到哪里"的表达式（讲义的绕口定义在这里被写成了一个 $\arg\min$）：

$$
x = \arg\min\left\{x : x > Q_1 - 1.5\,\mathrm{IQR}\right\}
$$

这个式子要逐字读：

- $\{x : x > Q_1 - 1.5\,\mathrm{IQR}\}$ 是"**所有严格大于下内栅栏的数据点**"构成的集合。用大白话说，就是把那些"还没掉出内栅栏"的点全部挑出来。
- 外面的 $\arg\min$ 表示"**在这个集合里取最小（最靠左）的那一个**"。
- 合起来：**下须的终点 = 所有"还没有越出下内栅栏"的数据点里最靠左的那个**。

这正是讲义"the larger one of lower inner fence and minimum"的意思，但**表达得更准确**：讲义的说法只在"最小的点在内栅栏以内"时才等价；而板书的写法自动处理了"最小点已经越出内栅栏"的情况——此时集合里最小的那个已经不是最小值了，而是内栅栏以内最靠左的那个点，下须就停在那里。

> 一个容易忽略的细节：板书写的是**严格不等号** $x > Q_1 - 1.5\,\mathrm{IQR}$。这意味着**恰好落在栅栏线上的点不被算进须里**。在实践中这种"恰好相等"的情形几乎不会发生（连续数据），但写严格的数学定义时必须交代清楚。

**（4）两级离群点阈值**：板书把两类阈值并列写成

$$
\text{potential outliers}: \quad \begin{cases} \le Q_1 - 1.5\,\mathrm{IQR}, & \text{or} \ge Q_3 + 1.5\,\mathrm{IQR} \\[4pt] \le Q_1 - 3\,\mathrm{IQR}, & \text{or} \ge Q_3 + 3\,\mathrm{IQR} \end{cases}
$$

对照讲义第 5 页的命名，这两行分别对应：

| 阈值（板书） | 讲义中的名称 | R `boxplot()` 里长什么样 |
| --- | --- | --- |
| 超出 $1.5\,\mathrm{IQR}$（内栅栏） | 可分两级：内栅栏~外栅栏之间为**可疑离群点**（suspected outlier）；外栅栏之外为**离群点**（outlier） | 全部画成单独的圆点 |
| 超出 $3\,\mathrm{IQR}$（外栅栏） | **离群点**（outlier）／常称"极端离群点" | 不区分，仍是圆点 |

**注意板书的措辞把两类都叫 "potential outliers"（潜在离群点）**，这不是笔误，而是一种更保守的态度：**超过 $1.5\,\mathrm{IQR}$ 只是"值得怀疑"，不构成"一定是异常"的证据。** 板书的用词其实更贴合统计学立场——离群点（outlier）本身是个**描述性**概念，**不等于错误数据（error）**。COVID 数据里那种"感染暴发日"的高计数是完全真实发生的事件，它离群但正确，**应该保留而不是删掉**。这一点在 3.4 节末尾已经提过（住宿学生组那个 $0.021$ 的极端 Rate 几乎独力撑起了整组标准差）。

**（5）板书还用一个小示意图强调了这一点**：须的两个端点都落在**真实数据点**上，而不是落在栅栏那条理论线上——这正是 $\arg\min\{x : x > Q_1 - 1.5\,\mathrm{IQR}\}$ 的几何含义。

---

## 3. 探索性数据分析实战：迈阿密大学 Covid-19 数据

讲义第 7 页把学生引到配套的 `Lec2_Covid.pdf`，用真实数据把所有工具跑一遍。这一节我把 R 代码逐句讲清楚，并给出**独立复算**的结果（我用 Python 重新跑了一遍这份 CSV，下面所有数值都核对过）。

### 3.1 数据与要回答的问题

数据来自迈阿密大学（University of Miami, UM）的 Covid-19 Community Dashboard，文件名 `UM_C19_2021.csv`，覆盖 **2020 年 8 月 16 日至 2021 年 8 月 15 日**，正好一个学年。

我核对了原始文件的规模：**共 1063 条逐日记录**，变量有 5 个：`Date`（日期）、`Type`（人员类别）、`residence`（居住类别）、`Positive`（当日阳性数）、`Negative`（当日阴性数）。（讲义正文说"收集了 Aug 16 2020–Aug 15 2021"，但**并不是每天都恰好有 3 条记录**：教职工/职员组 358 天、走读学生组 361 天、住宿学生组 344 天。这是个值得留意的数据质量问题——后面用 Poisson 做预测时，我们实际上是把"这一年记录到的阳性总数"当作"一年内的发生数"，中间的空缺日期被隐含地当作 0 处理了。）

`residence` 有三个取值，对应三个不同的人群（这是理解整个例子的前提）：

| `residence` 取值 | 对应人群 | 全校规模（讲义给出） |
| --- | --- | --- |
| `Non-Residential` | 教职工/职员（Faculty/Staff） | 约 16,000 人 |
| `Students - Non-Residential` | 住在校外的学生 | 约 13,000 人 |
| `Students - Residential` | 住校的学生 | 约 4,000 人 |

用这批数据要回答三个问题（第 7 页与 `Lec2_Covid.pdf` 第 1 页完全一致）：

1. **这批数据告诉我们 UM 的 Covid-19 感染情况是怎样的？**（描述性问题 → 用可视化 + 描述统计回答）
2. **若明年的阳性病例以与去年相同的速率到来，明年（整年）的阳性总数大概是多少？**（预测问题 → 用 Poisson 分布回答）
3. **若教职工的感染率维持去年的水平，那么统计系 20 位教职工中，明年会有多少位被感染？**（预测问题 → 用 Binomial 分布回答）

### 3.2 数据整理：R 代码逐句解释

**读入与查看**：

```r
covid = read.csv("UM_C19_2021.csv")
head(covid)
```

`read.csv()` 把 CSV 读成 data frame（数据框），`head()` 打印前 6 行，用来确认变量名和数据的形态。输出显示前 6 行是 8/16 和 8/17 两天、三组人群各一条。

**构造新变量**：

```r
covid$Total = covid$Positive + covid$Negative
```

`covid$Total` 表示"在 covid 这个数据框里新建（或访问）名为 Total 的列"；`$` 是 R 中访问列表/数据框元素的操作符。这一行把每天的**检测总数**算出来。

**按人群拆成三个对象**：

```r
covid_fs = covid[which(covid$residence == "Non-Residential"), ]
covid_ns = covid[which(covid$residence == "Students - Non-Residential"), ]
covid_rs = covid[which(covid$residence == "Students - Residential"), ]
```

这三行是 R 的语法重点，`Lec2_Covid.pdf` 第 2 页专门花了一段解释，值得完整掌握：

- `==` 是**关系运算符（relational operator）**，表示"判断是否相等"，返回 `TRUE`/`FALSE`。**绝对不能写成 `=`**，因为 `=` 在 R 里是赋值。这是初学者最常犯的错误之一，讲义原文也特别强调 "Please also note that `==` instead of `=` is used."
- `"Non-Residential"` 是被比较的字符串，**必须加引号**。讲义也专门提醒了这一点。
- `which(...)` 的作用是：把逻辑向量中为 `TRUE` 的**位置（下标）**提取出来。所以 `which(covid$residence == "Non-Residential")` 返回的是"哪些行是教职工/职员"的行号列表。
- `covid[行下标, 列下标]` 是数据框的方括号取子集语法。这里写成 `covid[行下标, ]`，**逗号后面留空表示"所有列都要"**，即保留整行记录。讲义的原话是 "The comma sign is used to keep the entire rows of records, i.e. all the variables."

验证一下（讲义第 2 页）：

```r
covid_fs[1:2, ]
```

输出显示取到的是原数据的第 1 行和第 4 行（8/16/2020 和 8/17/2020），都是 `Faculty/Staff / Non-Residential`，并且已经带上了新算出的 `Total` 列。**这里能看出 `which()` 返回的是"原始行号"，不是"重新编号后的 1、2"**——这正是为什么行名显示为 1 和 4。

```r
covid_fs$Date[1:2]
## [1] "8/16/2020" "8/17/2020"
```

`$Date` 先取出这一列，再用 `[1:2]` 取前两个元素。这演示了"先取列、再取元素"的两级索引方式。

**计算各组感染率**：

```r
covid_fs$Rate = covid_fs$Positive / 16000
covid_ns$Rate = covid_ns$Positive / 13000
covid_rs$Rate = covid_rs$Positive / 4000
```

这里要特别注意**分母是什么**：分母是**该人群的全校总人数**（教职工 16000、走读学生 13000、住宿学生 4000），**不是检测人数**。所以 `Rate` 的含义是"**当日每单位人口的阳性发生数**"，也就是**日发病率（daily incidence rate）**，单位是"每日每人"。因为分母固定为常数，`Rate` 与 `Positive` 只差一个常数倍，图形形状完全一样，只是数值刻度不同——这个理解在解读下面的 `sd()` 输出时很关键。

### 3.3 描述性统计：`summary()`

```r
summary(covid_fs[, 4:7])
```

- `covid_fs[, 4:7]` 与前面不同：**逗号前面留空表示"所有行"，逗号后面写 `4:7` 表示"第 4 到第 7 列"**（即 `Positive`、`Negative`、`Total`、`Rate`）。讲义原文也提示了这一点："the comma sign is being used so that the entire columns (not rows anymore) would be included."
- `summary()` 对数值型变量输出经典的六个数：**Min.（最小值）、1st Qu.（$Q_1$）、Median（中位数）、Mean（均值）、3rd Qu.（$Q_3$）、Max.（最大值）**——正好把直方图和箱线图需要的描述统计一次性给全。

三组人群的完整输出如下（我把讲义的三段输出整理成一张表，全部数值已用 Python 独立复算验证）：

**教职工/职员（Faculty/Staff, `covid_fs`）**

| 统计量 | Positive | Negative | Total | Rate |
| --- | --- | --- | --- | --- |
| Min. | 0.000 | 0.00 | 0.00 | 0.0000000 |
| 1st Qu. | 0.000 | 23.00 | 24.00 | 0.0000000 |
| Median | 1.000 | 61.00 | 63.00 | 0.0000625 |
| Mean | 2.201 | 64.71 | 66.91 | 0.0001376 |
| 3rd Qu. | 3.000 | 102.00 | 105.00 | 0.0001875 |
| Max. | 17.000 | 188.00 | 200.00 | 0.0010625 |

**走读学生（Students - Non-Residential, `covid_ns`）**

| 统计量 | Positive | Negative | Total | Rate |
| --- | --- | --- | --- | --- |
| Min. | 0.000 | 0.0 | 0.0 | 0.000e+00 |
| 1st Qu. | 1.000 | 46.0 | 50.0 | 7.692e-05 |
| Median | 2.000 | 107.0 | 110.0 | 1.538e-04 |
| Mean | 4.238 | 275.2 | 279.5 | 3.260e-04 |
| 3rd Qu. | 6.000 | 469.0 | 478.0 | 4.615e-04 |
| Max. | 52.000 | 1212.0 | 1234.0 | 4.000e-03 |

**住宿学生（Students - Residential, `covid_rs`）**

| 统计量 | Positive | Negative | Total | Rate |
| --- | --- | --- | --- | --- |
| Min. | 0.000 | 0.0 | 0.0 | 0.0000000 |
| 1st Qu. | 0.000 | 22.0 | 22.0 | 0.0000000 |
| Median | 1.000 | 53.0 | 55.0 | 0.0002500 |
| Mean | 3.422 | 186.6 | 190.0 | 0.0008554 |
| 3rd Qu. | 4.000 | 378.2 | 380.8 | 0.0010000 |
| Max. | 84.000 | 958.0 | 1042.0 | 0.0210000 |

**从这张表能读出什么**（这部分是我基于输出做的解读，讲义只给了代码和输出，没有展开）：

- **均值显著大于中位数**，三组的 `Positive` 都是 `Mean > Median`（例如教职工 2.201 vs 1.000，住宿学生 3.422 vs 1.000）。这是**右偏（right-skewed）**的典型信号——一批特别大的观测把均值往上拽，而中位数不受影响。这和 3.5 节直方图看到的"右偏"完全一致。
- **中位数低到 1–2**，且 $Q_1$ 常常是 0，说明**绝大多数日子阳性数很少**（大多数时候是 0 或 1 例），感染是"偶发且偶尔爆发"的模式。最大值却是 17 / 52 / 84，说明极少数日子会集中爆发。
- **走读学生的检测量远大于其他两组**（`Negative` 均值 275.2，最大值 1212），住宿学生居中（186.6），教职工最少（64.71）。这合理：教职工人虽多（16000），但日常不需要频繁检测。
- **Rate 的数值量级**：教职工均值 $1.376\times10^{-4}$，即平均每天每万人中有约 1.4 例，换成"每日每 10 万人"约 13.8 例——这是校内筛查口径下的发病率，**不能直接跟社会面上的发病率比较**，因为分母口径不同（这里是全部人口当分母、只统计主动检测出的阳性）。

### 3.4 波动性比较：`sd()`

```r
sd(covid_fs$Rate) * 100   # 0.01779956
sd(covid_ns$Rate) * 100   # 0.04641223
sd(covid_rs$Rate) * 100   # 0.1942217
```

`sd()` 计算**样本标准差（sample standard deviation）**，注意它用的是 $n-1$ 分母（无偏版本），不是 $n$。我复算的结果与讲义**完全一致**：$0.0177996$ / $0.0464122$ / $0.1942217$，验证无误。

乘 100 只是为了把数放大到方便读，因为原值都是 $10^{-4}$ 量级。

这三个数比较的是**感染率（Rate）的波动**，先做一个朴素的对照：三组的 std 依次是 $0.0178 < 0.0464 < 0.1942$，**住宿学生的波动最大，教职工最小**。结合 3.3 节，教职工的均值也最小（$1.376\times10^{-4}$），住宿学生均值最大（$8.554\times10^{-4}$）——也就是说，**哪个组的平均感染率高，其波动也大**。

但要下"谁更不稳定"的结论，光比绝对标准差是不够的，因为均值不同。更公平的做法是看**变异系数（coefficient of variation, CV = 标准差 / 均值）**：

$$
CV_{fs} = \frac{0.0178\%}{0.01376\%} \approx 1.29, \quad
CV_{ns} = \frac{0.0464\%}{0.03260\%} \approx 1.42, \quad
CV_{rs} = \frac{0.1942\%}{0.08554\%} \approx 2.27
$$

（注意这里的分子分母都带同一个 $\times100$ 或 $\times10^{-2}$ 因子，相除后抵消，所以直接用上面打印出来的数算即可。）看出来了吗：**即使按相对波动看，住宿学生仍然是遥遥领先的最大动荡源（CV≈2.27）**。这与"宿舍是集体居住、接触密集，一旦暴发就成簇传播"的现实直觉吻合。

> 这里补一个重要提醒（讲义未提，但对你后面理解预测部分很关键）：**住宿学生这一组的 Rate 里有一个 $0.021$ 的极端值**（见 3.3 表的 Max. 行），而这一组的中位数只有 $0.00025$。也就是说最大值是中位数的 **84 倍**。这一个（或少数几个）极端观测，几乎独力撑起了住宿学生组的大部分标准差。**这正是"标准差不是稳健统计量"的教科书级例子**——IQR 比 sd 更能代表这种情况下的"典型波动"。

### 3.5 直方图输出与解读（`Lec2_Covid.pdf` 第 4 页）

```r
par(mfrow = c(2, 3))
hist(covid_fs$Positive, xlab = "positive", main = "Faculty/Staff")
hist(covid_ns$Positive, xlab = "positive", main = "Non-Residential Students")
hist(covid_rs$Positive, xlab = "positive", main = "Residential Students")
hist(covid_fs$Total,    xlab = "total",    main = "Faculty/Staff")
hist(covid_ns$Total,    xlab = "total",    main = "Non-Residential Students")
hist(covid_rs$Total,    xlab = "total",    main = "Residential Students")
```

- `par()` 用来设置**图形参数**；`mfrow = c(2, 3)` 表示"之后的所有图按 **2 行 3 列**的网格排列"。所以上面六条 `hist()` 会被铺成两行：**第一行三张是每日阳性数，第二行三张是每日检测总数**，列的方向统一是"教职工 / 走读学生 / 住宿学生"。这种布局的好处是**行内可比（同一指标跨人群）、列内可比（同一人群跨指标）**。
- `hist()` 的三个参数：第一个是数据向量，`xlab` 是横轴标签，`main` 是图标题。

**讲义给出的解读（第 4 页末尾）：**

> "Note that the daily positive counts are all skewed to the right, while the daily total tests are not as skewed. The daily total tests for residential students in fact seems to have two peaks."

翻成中文并补上细节：

- **第一行三张（每日阳性数）全部右偏（skewed to the right）**。图上表现为：柱子集中在左边（0、1、2 附近）急剧升高，然后向右拉出一条长而稀疏的尾巴。教职工组最大值 17、走读学生组 52、住宿学生组 84，这些极端值就是尾巴。
- **第二行三张（每日检测总数）偏度明显更小**。检测数是由"学校的检测安排"决定的（工作日多、周末少之类的行政节律），波动相对温和，不会像感染那样出现数量级的爆发，所以分布更接近对称。**这是一个很好的方法论示范：同一批人群的两类变量，分布形状可以完全不同，说明分布形状是由背后的生成机制决定的，不能想当然。**
- **住宿学生的每日检测总数"看起来有两个峰"（bimodal）**。这是个很有意思的发现：可能是"上课日 vs 周末"两种检测安排造成的混合分布。**这是纯粹靠 EDA 才能发现、而单看均值/标准差完全看不到的结构**——回到第 1.2 节讲义强调的那句话，组距选得对（不过大），才可能有这种发现。

**这段 EDA 与后文的因果关系**：注意，阳性数是**右偏**的。而 Poisson 分布本身也是右偏的（尤其是均值不大时）。所以第 4 节用 Poisson 去建模"阳性总数"不是随便挑的——**直方图给出的形状信息，正是选择分布模型的依据**。讲义第 8 页那句 "Histogram tells us that the sample is likely drawn from a normal population $N(\mu,\sigma^2)$" 说的就是这个逻辑：**用直方图的形状去猜总体分布族（model selection），再用参数估计去定参数（parameter estimation）。**

### 3.6 箱线图输出与解读（`Lec2_Covid.pdf` 第 5 页）

```r
par(mfrow = c(2, 1))
boxplot(covid$Positive ~ covid$residence, xlab = "residence", ylab = "Positive Counts")
boxplot(covid$Total    ~ covid$residence, xlab = "residence", ylab = "Total Tests")
```

- `par(mfrow = c(2, 1))`：两行一列（上下两张）。
- **`boxplot(Y ~ X)` 的公式语法是重点**。讲义原文解释得清楚：`Y ~ X` 读作"Y by X"，意思是**按 X 的取值把 Y 分组，各组分别画一个箱线图**。其中 **X 通常是定性变量（qualitative variable，分类变量）**，本例里就是 `residence`（只有三个取值）。这一行等价于"我要看三组人群的阳性数各自的箱线图，并排放在一起"。旁边的 `xlab` / `ylab` 分别是横轴（这里横轴刻度是分类名）和纵轴标签。
- 注意这里用的是**原始的 `covid` 数据框**（不是拆分的 `covid_fs` 等），因为公式语法本身就会按 `residence` 自动分组。
- 下面那张图的 `ylab` 是 `"Total Tests"`，但**纵轴实际画的是 `covid$Total`，也就是"当日检测总数（阳性 + 阴性）"**，不是"阳性总数"。读图时按"检测量"理解。

**这两张箱线图能读出什么**（讲义未展开，我按第 2.3 节的读图规则解读）：

- **三个箱体都严重集中于纵轴底部**，而须向上延伸得很远。这就是 3.3 节"均值 > 中位数、右偏"在箱线图上的直接体现：**上须远长于下须**，而且上须外侧通常还挂着若干离群点。
- **所有箱体的下边缘（$Q_1$）都贴着 0**（教职工组和住宿学生组的 $Q_1$ 就是 0，走读学生组是 1），中位数也只在 1–2 附近。这再次印证：**大多数日子是零病例或个位数病例。**
- **检测总数（下图的纵轴范围到 1000+）与阳性数（上图纵轴只到 80）相差一个数量级**，所以两张图必须分开画、各用自己的刻度，不能放在同一坐标轴上比较。这也解释为什么第 3.4 节要用 `Rate`（除以人口，归一化）而不是直接用原始计数做跨组比较。
- **箱线图比直方图更适合"跨组比较"**：六张直方图要横竖对比，人眼容易累；换成两张箱线图，三个组的中心位置、箱体宽窄、须长短、离群点多少全部并排在同一尺度上，一眼可比。这正是第 2 节开头说的箱线图的定位。

---

## 4. 从描述到预测：两个分布的应用

第 3 节做的事是**描述（description）**——把数据"说清楚"。接下来讲义用两个具体问题把课程推进到**推断（inference）**：用去年的数据去**预测**明年会发生什么。这是本讲最关键的转折点，也是引出 MLE 的引子。

### 4.1 用 Poisson 分布预测明年教职工的阳性总数

**建模思路**：把"明年一整年教职工的阳性总数"看成一个随机变量 $X$。阳性病例在一年的时间里以某种"速率"零星发生，彼此近似独立、不发生重叠计数——这种"**稀有事件在固定时间窗内发生的次数**"的标准模型就是 Poisson 分布：

$$
P(X = k) = \frac{e^{-\lambda}\lambda^k}{k!}, \quad k = 0, 1, 2, \ldots
$$

（这个分布的完整性质在第 1 讲笔记的第 4.2 节讲过：$E[X] = \mathrm{Var}(X) = \lambda$，$\lambda$ 是"单位时间内的平均发生次数"，且 $\lambda$ 越大分布越接近对称的正态。）

**剩下唯一的问题：$\lambda$ 取多少？** 讲义的做法只有一行：

```r
mu = sum(covid_fs$Positive)
```

也就是**把去年一整年教职工的阳性数全部加起来**。我复算过：$\sum \text{Positive} = 788$。

于是得到 $\lambda = 788$。这个做法的逻辑是：**"假设明年的速率和去年一样"**（讲义原话 "Suppose that the positive cases for the next year will arrive at the same rate as the last year included in the data"），那么明年一年的期望发生次数就等于去年一年的实际发生次数。**注意这里用"观测到的总数"当作"期望"，是一种非常粗糙但直觉上说得通的估计方式**——请记住这个动作，第 5 节之后我们会问：这种做法有理论依据吗？有没有更好的？

**计算各种概率**（讲义给出三种问法的代码）：

```r
ppois(400, mu)                        # P(X <= 400)  = 7.701494e-53
ppois(800, mu)                        # P(X <= 800)  = 0.6736617
ppois(800, mu) - ppois(400, mu)       # P(400 < X <= 800) = 0.6736617
1 - ppois(800, mu)                    # P(X > 800)   = 0.3263383
ppois(800, mu, lower.tail = FALSE)    # P(X > 800)   = 0.3263383
```

逐条解释：

- `ppois(k, lambda)` 是 Poisson 的**累积分布函数（CDF）**，返回 $P(X \le k)$。R 里所有分布函数有一套统一命名：`d` 前缀是密度/质量函数（如 `dbinom`）、`p` 前缀是 CDF（如 `ppois`）、`q` 前缀是分位数函数（quantile function，CDF 的逆）、`r` 前缀是随机数生成（如 `rpois`）。记住这个 `d/p/q/r` 规律，R 里十几种分布的用法就全通了。
- **$P(X \le 400)$ 算出来是 $7.7 \times 10^{-53}$**，这是一个**小到荒谬的数**。它的含义是：如果明年真的还是 $\lambda = 788$ 的速率，那么"全年阳性总数不超过 400"这件事**几乎不可能发生**（概率是小数点后 52 个零）。这其实是一个很实用的诊断信号——**说明 400 这个门槛相对于 788 来说偏得太远了。**
- **$P(X \le 800) = 0.6736617$**，即约 **67.4%** 的概率明年总数不超过 800。
- **$P(400 < X \le 800) = P(X\le800) - P(X\le400) = 0.6736617 - 7.7\times10^{-53} \approx 0.6736617$**。这里有个容易被误认为"讲义算错了"的地方：**输出看起来跟 $P(X \le 800)$ 一模一样**。原因不是算错，而是**浮点数的精度限制**：R 用双精度浮点（约 16 位有效数字）存储数字，$7.7\times10^{-53}$ 相对于 $0.6736617$ 小到完全无法在减法中体现出来，相减后结果就是 $0.6736617$ 原封不动。**数学上两者不等，计算机上两者相等**——这是数值计算里非常典型的现象，考场上不必纠结。
- **$P(X > 800)$ 有两种算法**（讲义特意给了两种，是为了讲 R 的用法）：
  - 第一种：`1 - ppois(800, mu)`，即用补事件：$P(X>800) = 1 - P(X\le 800)$。
  - 第二种：`ppois(800, mu, lower.tail = FALSE)`。参数 `lower.tail = FALSE` 表示**"计算上尾（upper tail）的概率"**，也就是 $P(X > 800)$，直接算而不用做减法。
  - 两者结果都是 $0.3263383$，即约 **32.6%** 的概率明年总数超过 800。
  
  **为什么讲义要专门介绍 `lower.tail = FALSE`？** 因为当 $P(X\le k)$ 极其接近 1 时，用 `1 - ppois(...)` 会遭遇**灾难性抵消（catastrophic cancellation）**：两个非常接近的浮点数相减，有效数字大量丢失，相对误差可能变得很大。直接算上尾能避免这个问题。**这是一个非常好的数值计算习惯，值得记住。**

**结论（如何回答第 2 个问题）**：如果明年的感染速率与去年相同，那么明年教职工的阳性总数有约 **67%** 的概率落在 $(400, 800]$ 区间内，有约 **33%** 的概率超过 800，几乎不可能低于 400。**最可能落在 788 附近**（因为 Poisson 的均值就是 $\lambda$）。

### 4.2 用 Binomial 分布预测统计系 20 位教职工的感染人数

**建模思路**：这次问的不是"全校教职工总共多少例"，而是**"统计系的 20 位教职工里，有几位会被感染"**。这是一个"**在 $n$ 个个体中数成功的个数**"的问题，标准模型是二项分布（Binomial distribution）：

$$
P(X = k) = \binom{n}{k}p^k(1-p)^{n-k}, \quad k = 0, 1, \ldots, n
$$

其中：$n$ 是试验次数（这里是人数，$n = 20$）；$p$ 是**单次试验的成功概率**（这里是"某一位教职工在这一年里被感染的几率"）；$X$ 是成功次数（被感染的人数）。二项分布的期望是 $E[X] = np$。

**关键难点：$p$ 从哪来？** 讲义的做法：

```r
p = sum(covid_fs$Positive) / 16000
```

即 **$p = 788 / 16000 = 0.04925$**。逻辑是：去年全校 16000 名教职工里总共出现了 788 例阳性，所以"一年内某位教职工被测出阳性"的概率约为 $788/16000 \approx 4.9\%$。

> 这里有个**隐含的建模假设需要点明**（讲义没写，但这是理解 Binomial 是否适用的关键）：把"16000 人里出 788 例"直接当成"每个人的感染概率是 $788/16000$"，等价于假设**每位教职工最多被感染一次、且各人之间独立同分布**。前半个假设基本合理（"阳性例数"通常按人计），后半句"各人独立"在传染病场景下是**明确不成立的**（同办公室、同宿舍会成簇感染），这也正是后面 COVID 传播研究要用过度离散（overdispersion）模型的原因。**作为课堂练习用 Binomial 是合适的，但要知道这是个简化假设。**

**计算**：

```r
dbinom(0, 20, p)          # P(X = 0) = 0.3641889
1 - pbinom(1, 20, p)      # P(X >= 2) = 0.2585026
pbinom(1, 20, p, lower.tail = FALSE)   # P(X > 1) = P(X >= 2) = 0.2585026
```

- `dbinom(k, size, prob)` 是二项分布的**概率质量函数（PMF）**，直接给 $P(X = k)$。参数名要记清：第二个参数是 `size`（试验次数 $n$），第三个是 `prob`（单次成功概率 $p$）——**顺序不能颠倒**。
- `pbinom(k, size, prob)` 是二项分布的 CDF，给 $P(X \le k)$。
- $P(X \ge 2) = 1 - P(X \le 1)$：讲义还特别点出 "or equivalently $P(X>1)$ or $1 - P(X\le1)$"，即 $\{X \ge 2\}$、$\{X > 1\}$ 和 $\{X \le 1\}$ 的补集是**同一件事**（因为 $X$ 只能取整数值）。**这类"离散取值的边界转移"在作业里极易写错**：对整数型随机变量，$X \ge 2 \iff X > 1$，所以 $1 - P(X\le 1) = P(X > 1) = P(X\ge 2)$，三者完全等价。写成 $1 - P(X \le 2)$ 就错了（那是 $P(X\ge 3)$）。
- `lower.tail = FALSE` 在这里的作用与前面 Poisson 一致：直接给上尾概率 $P(X > 1)$。

**完整的分布列**（讲义用 `support = 0:20` 生成 0 到 20 的所有取值，`dbinom(support, 20, p)` 一次算出所有概率，再用 `cbind(support, prob)` **按列合并**成两列矩阵打印出来）。整理成表：

| 感染人数 $k$ | $P(X=k)$ | | 感染人数 $k$ | $P(X=k)$ |
| --- | --- | --- | --- | --- |
| 0 | 3.641889e-01 | | 11 | 4.408303e-10 |
| 1 | 3.773085e-01 | | 12 | 1.712666e-11 |
| 2 | 1.856778e-01 | | 13 | 5.459579e-13 |
| 3 | 5.771002e-02 | | 14 | 1.414064e-14 |
| 4 | 1.270516e-02 | | 15 | 2.930009e-16 |
| 5 | 2.106056e-03 | | 16 | 4.743063e-18 |
| 6 | 2.727406e-04 | | 17 | 5.781092e-20 |
| 7 | 2.825659e-05 | | 18 | 4.991126e-22 |
| 8 | 2.378554e-06 | | 19 | 2.721540e-24 |
| 9 | 1.642826e-07 | | 20 | 7.048954e-27 |
| 10 | 9.361043e-09 | | | |

我独立复算过 $P(X=0) = 0.3641889$、$P(X=1) = 0.3773085$、$P(X\ge2) = 0.2585026$，与讲义**完全一致**。

**结论（如何回答第 3 个问题）**：

- **"统计系 20 位教职工无一人被感染"的概率是 36.4%**（$P(X=0) = 0.364$）。
- **最可能的结果是正好 1 人被感染**，概率 37.7%——略高于"零人"。
- **"至少 2 人被感染"的概率是 25.9%**（$P(X\ge2) = 0.2585$）。**这大约 1/4 的概率，说明"系里一年内出现两例以上"并不是小概率事件，不该被当成异常。**
- 做一个快速合理性检查：$E[X] = np = 20 \times 0.04925 = 0.985$，期望约等于 1 人，与"$P(X=1)$ 最大"的结论互相印证。**养成这种"算完概率后用期望做量级校验"的习惯，能有效防止把参数顺序写反之类的错误。**

（顺带一提：第 4.1 节的 $\lambda=788$ 和第 4.2 节的 $p=788/16000$ 用的是**同一个 788**，但两个模型的假设并不完全兼容——前者假设"病例按时间以恒定速率到达"，后者假设"每个人独立地有一次感染机会"。同一批数据在不同模型下可以有不同的解释，**模型的适用性取决于你要问的问题，而不是数据本身唯一决定的**。这是统计建模的元认知，比具体公式更重要。）

### 4.3 这两个估计的"临时性"——引出下一节

现在回头看这两节的估计动作：

$$
\hat\lambda = \sum_{i=1}^{n} X_i \qquad (\text{Poisson 的均值})
\qquad\qquad
\hat{p} = \frac{\sum_{i=1}^{n} X_i}{16000} \qquad (\text{感染概率})
$$

它们都是**"凭直觉凑出来"的估计量**：用观测总数当期望、用样本比例当概率，看起来挺合理，但我们**完全不知道它们好在哪、有没有更好的、能不能证明它们的性质**。而且我们后面还会遇到别的分布（正态、Gamma、Weibull……），总不能每碰上一个分布就临场想一个估计公式。

**统计学的回答是：给出一套通用的、有理论保证的"估计算法"。这套算法就是极大似然估计（MLE）——本讲剩余部分的全部内容。** 具体来说：

- 第 5 节搭框架：参数空间、估计量 vs 估计值。
- 第 6 节构造工具：似然函数与对数似然。
- 第 7 节给方法：MLE 的定义与四个例子。
- 第 8 节给理由：为什么最大化似然是**对**的做法（这需要一组正则条件和一个极限定理）。

---

## 5. 参数估计的基本框架

### 5.1 问题设定（讲义第 8 页）

讲义第 8 页把整个问题的背景交代得很简洁：

> "Suppose we have a sample with size $n$ from a population. Histogram tells us that the sample is likely drawn from a normal population $N(\mu, \sigma^2)$. How to estimate the population parameters $(\mu, \sigma^2)$?"

这段要拆成三层来理解：

**第一层：我们的处境。** 手上有样本量（sample size）为 $n$ 的一组样本，来自某个总体（population）。**总体是不可观测的**（我们不可能去测所有人的身高），我们只能看到样本。

**第二层：直方图告诉我们分布族。** 把样本画成直方图，**形状像钟形**，于是推断样本很可能来自正态总体 $N(\mu,\sigma^2)$。这是第 1 节讲的"柱子的面积对应概率"那个联系的直接应用——**从经验分布（empirical distribution）的形状，反推总体的分布族（distribution family）**。

**第三层：剩下来的是参数。** 一旦认定总体是正态，那么"总体长什么样"就完全由两个数决定：$\mu$（均值）和 $\sigma^2$（方差）。**这两个数就是参数（parameters）**——它们属于总体，是固定的（在这个框架下被视为常数，而不是随机变量），但我们**永远不知道它们的真值**。于是问题变成：**用样本去估计 $(\mu,\sigma^2)$。**

讲义在第 8 页还给了一个**必须记住的假设清单**（原文 "Assumptions"）：

1. **the sample is representative of the population**（样本能代表总体）——否则后面所有推断都是空中楼阁。
2. **the data are normally distributed**（数据服从正态分布）——即分布族的选择正确。

这两个假设就是本讲所有理论建立的"地基"。注意它们是**假设**：如果直方图看起来不像正态，或者样本是通过某种有偏的方式收集的，那么这里发展出来的一切都失去意义。**在实际数据分析中，验证这两个假设（至少用直方图/QQ 图目视检查）是必须的一步。**

### 5.2 参数空间（Parameter Space，讲义第 9 页）

讲义第 9 页把设定正式化了：

> "Suppose we have a random sample $X_1, X_2, \ldots, X_n$ i.i.d. from a population distribution with unknown parameter $\theta$ and PMF or PDF $f(x;\theta)$. The parameter $\theta$ takes values in the parameter space $\Omega$."

逐项解释这些记号：

- **$X_1, X_2, \ldots, X_n$**：$n$ 个随机变量，代表"抽 $n$ 次"的结果。
- **i.i.d.**：independent and identically distributed，**独立同分布**（第 1 讲笔记里出现过）。两个条件缺一不可：
  - **independent（独立）**：抽到第 $i$ 个观测的结果不影响第 $j$ 个。这个条件保证了后面**联合分布可以写成各个边际分布的乘积**（这是构造似然函数的合法性来源，见 6.1 节）。
  - **identically distributed（同分布）**：每个 $X_i$ 来自同一个总体、同一组参数。这个条件保证了"用同一条曲线 $f(x;\theta)$ 描述每一个 $X_i$"是合法的。
  - **这两个条件就是本讲一切推导的隐含前提。** 如果样本不独立（比如时间序列上的自相关）或不同分布（比如混了男女生但分开看分布不同），下面的公式就都不成立。
- **$\theta$**：**未知参数（unknown parameter）**。它可以是标量（例如 Bernoulli 的 $p$），也可以是向量（例如正态的 $(\mu,\sigma^2)$，两个分量）。**下面所有推导都写成标量 $\theta$ 的形式，向量情形把求导换成求偏导即可，逻辑完全一样。**
- **$f(x;\theta)$**：总体的 PMF（离散）或 PDF（连续）。**分号后的 $\theta$ 是关键**：它表示"这个分布族依赖于参数 $\theta$"。同一个函数形式，$\theta$ 取不同的值就得到一族不同的分布，所以 $f(\cdot;\theta)$ 描述的是**一族分布（a family of distributions）**。
- **$\Omega$（大写希腊字母 Omega）**：**参数空间（parameter space）**，即"$\theta$ 所有**允许**取值的集合"。**为什么必须显式写出 $\Omega$？** 因为它会在求解 MLE 时起到硬约束的作用——最大化时只能挑 $\Omega$ 里面的值。讲义第 6.1 节的 Uniform 例子就是"约束真的卡住最优点"的经典案例。

**讲义给的例子（正态分布）**：正态的 PDF 是

$$
f(x) = \frac{1}{\sigma\sqrt{2\pi}}\exp\left[-\frac{(x-\mu)^2}{2\sigma^2}\right], \quad -\infty < x < \infty
$$

这里 $\theta = (\mu, \sigma^2)$，对应的参数空间是

$$
\Omega = \{(\mu, \sigma^2) : -\infty < \mu < \infty,\ 0 < \sigma^2 < \infty\}
$$

**注意 $\Omega$ 里写的是什么、为什么这么写**：

- $\mu$ 可以取任意实数，所以是 $(-\infty, \infty)$（**开区间**）。
- $\sigma^2$ **只能取正数**——方差不可能为负（也不可能为零，否则分布退化成一个点，不再是连续分布）。所以写成 $0 < \sigma^2 < \infty$，**下端点 0 取不到**。
- 更精细地说，$\mu$ 的对称性也是这个参数空间的隐含结构，但讲义没有深入。

**这个例子的方法论意义**：$\Omega$ 不仅是个"取值范围"的形式说明，它明确告诉我们在做优化时**疆界在哪**。后面 Uniform 例子里最优解会被推到一个端点（$\hat\theta = \max X_i$），正是 $\Omega$ 的边界在起作用。

### 5.3 估计量 vs 估计值（Estimator vs Estimate，讲义第 10 页）

讲义第 10 页引入了一套记号，并且**这页的每一条都值得记牢**，因为整个学期都会反复用：

> "The observed values of $X_1, X_2, \ldots, X_n$ are denoted as $x_1, x_2, \ldots, x_n$."

**这是统计学里最基础的"大小写约定"**：

| 写法 | 名称 | 性质 | 例子 |
| --- | --- | --- | --- |
| 大写 $X_i$ | **随机变量（random variable）** | 在抽样**之前**，结果是未知的，是随机的 | "下一位被测者的身高" |
| 小写 $x_i$ | **观测值（observed value / realization）** | 抽样**之后**，已经拿到手的确定数值 | 我实际测到 172.5 cm |

讲义原文专门用一句强调这一点：**"Note that $X_i$ is a random variable, while $x_i$ represents the actual value of $X_i$ in a sample."** 这句话看似废话，实际上是理解"估计量的抽样分布"的关键——**因为 $X_i$ 是随机变量，所以由它构造的函数（也就是估计量）也是随机变量，也有自己的分布。** 这一点在下一讲（无偏性、有效性）会成为主角。

> "The statistics $u(X_1, X_2, \ldots, X_n)$ to estimate $\theta$ is also called an **estimator** of $\theta$."

- **统计量（statistic）**是"**样本的函数**"，而且**不能含有任何未知参数**。$u(X_1,\ldots,X_n)$ 就是这个函数的一般写法。
- **估计量（estimator）**：当这个统计量被用来估计 $\theta$ 时，就叫 $\theta$ 的估计量。
- **核心：估计量是随机变量**，因为它的自变量 $X_1,\ldots,X_n$ 都是随机变量。**同一套抽样规则、抽不同的样本，会得到不同的估计值。**
- 记号惯例：估计量常写作 $\hat\theta$（读作 "theta hat"），或 $u(X_1,\ldots,X_n)$。

> "The value of $u(x_1, x_2, \ldots, x_n)$ is said to be an **estimate** of $\theta$."

- **估计值（estimate）**：把实际观测到的数代进去算出来的那**一个具体数字**。它是一个常量，不是一个分布。

**一句话区分**：**估计量是"规则"（带随机性的函数），估计值是"这一次算出来的数"（确定的值）。** 举例：$\bar X = \frac{1}{n}\sum X_i$ 是均值的一个**估计量**；你在某次抽样中算出 $\bar x = 172.5$，172.5 就是一个**估计值**。

> "Since $u(X_1, X_2, \ldots, X_n)$ is a single value estimator of $\theta$, it is called a **point estimator**."

- **点估计量（point estimator）**：输出**单个值**的估计。（与之相对的是**区间估计（interval estimator）**，输出一个区间，那是后面几讲的内容。）讲义这句话的意思是：因为我们只用一个数去"点对点"地代表 $\theta$，所以叫点估计。
- 对应的，$u(x_1,\ldots,x_n)$ 具体算出来的数叫**点估计值（point estimate）**。

**把这三个层级串起来看**（这是本页最重要的收获）：
$$
\underbrace{u(X_1,\ldots,X_n)}_{\text{统计量 / 点估计量：随机变量}}
\ \xrightarrow{\ \text{代入具体样本}\ }\
\underbrace{u(x_1,\ldots,x_n)}_{\text{点估计值：一个数}}
\ \xrightarrow{\ \text{用来猜}\ }\
\underbrace{\theta}_{\text{真参数：永远不知道}}
$$

### 5.4 板书补充：估计量的评价标准（Bias / Var / MSE / Consistency）

这一节来自课堂抄录笔记。板书写下了三行：

$$
\textbf{Estimator}: \hat\theta = u(x_1,\ldots,x_n), \qquad
\textbf{Estimate}: u(x_1,\ldots,x_n), \qquad
\textbf{Criteria}: \text{Unbiased},\ \text{Consistent}
$$

前两行与 5.3 节完全对应，**第三行 `Criteria` 是新信息**——它在问一个 5.3 节没有回答的问题：**"怎么判断一个估计量是好是坏？"** 板书的答案给了四个量：偏差、方差、均方误差、相合性。

> **重要定位**：本节只把这些指标**列出来并解释含义**。真正的"用它们比较估计量"是**下一讲（第 3 讲）**的主题。板书写下 `Criteria` 就是给下一讲埋的钩子（正文 7.8 节末尾也提到过这一点）。现在读这一节的目标是"**看到这些符号不陌生**"，而不是"会用它们做题"。

#### 5.4.1 偏差（Bias）——衡量"平均准不准"

$$
\text{Bias}(\hat\theta) = E(\hat\theta) - \theta
$$

逐字读这个式子：

- $\theta$ 是**真参数**（固定常数，我们永远不知道）。
- $E(\hat\theta)$ 是**估计量的期望**。注意 $\hat\theta$ 是随机变量（5.3 节的大小写约定），所以它可以取期望——含义是"**如果我把整个抽样过程重复无数次，每次算一个 $\hat\theta$，这些值平均下来是多少**"。
- 两者相减，衡量的是**系统性偏离**。

**若 $\text{Bias}(\hat\theta) = 0$，即 $E(\hat\theta) = \theta$，则称 $\hat\theta$ 为 $\theta$ 的*无偏估计量*（unbiased estimator）**。

> **打靶类比（这是理解这三个量最快的方式）**：
>
> - **Bias 管"圆心偏没偏"**——弹着点分布的中心离靶心有多远。
> - **Var 管"散得开不开"**——弹着点之间有多散。
> - 两者互相独立：可以又偏又散，也可以又准又稳。

**无偏的一个关键澄清**：无偏**不**意味着"这次估得准"。它说的是**长期平均**的行为——单次抽样照样可能离 $\theta$ 很远。**无偏 ≠ 每次都对，无偏 = 平均下来不偏。**

**两个必须记住的例子**（都在前面的笔记里出现过）：

- $S^2 = \frac{1}{n-1}\sum_{i=1}^n (X_i-\bar X)^2$ 是**无偏**的（第 1 讲 8.6 节讲过：分母取 $n-1$ 正是为了让 $E[S^2]=\sigma^2$）；若把分母换成 $n$，则**有负偏差**（系统性低估方差）。
- Uniform $[0,\theta]$ 的 MLE $\hat\theta = X_{(n)}$ **有偏**（第 7.6 节）：$E[X_{(n)}] = \frac{n}{n+1}\theta < \theta$，系统性偏低。但它**渐近无偏**。

#### 5.4.2 方差 $\operatorname{Var}(\hat\theta)$——衡量"抖不抖"

$$
\operatorname{Var}(\hat\theta) = E\!\left[\left(\hat\theta - E\hat\theta\right)^2\right]
$$

> ⚠️ **抄录勘误**：你的笔记里这一行写成了 $E(\hat\theta - E\hat\theta)$，**漏了平方**。方差必须是**平方**的期望。原因：$E(\hat\theta - E\hat\theta) = E\hat\theta - E\hat\theta = 0$ **恒等于 0**，这个量不携带任何信息。这里按方差的定义补上平方号。

- 它衡量的是"**估计量自身有多抖**"——重复抽样时，$\hat\theta$ 的值在**它自己的均值**附近散布得多宽。
- **注意它和 Bias 的分工**：Bias 拿 $\hat\theta$ 和**真值 $\theta$** 比；Var 拿 $\hat\theta$ 和**它自己的均值 $E\hat\theta$** 比。**方差完全不关心均值对不对。**
- 方差小 = **精确（precise）**；无偏 = **准确（accurate）**。中文里"精确"和"准确"常被混用，但在统计里是两个不同的东西，对应这两个量。

#### 5.4.3 均方误差 MSE 与偏差–方差分解（本块板最有价值的一行）

$$
\operatorname{MSE}(\hat\theta) = E\!\left[\left(\hat\theta - \theta\right)^2\right]= \operatorname{Var}(\hat\theta) + \left[\text{Bias}(\hat\theta)\right]^2
$$

> ⚠️ **抄录勘误**：你的笔记里写成了 $MSE(\theta) = E(\theta-\theta)^2$。两处要改：① 左边的 $\theta$ 应为 $\hat\theta$（被评价的是估计量，不是参数）；② 括号里第一个 $\theta$ 也应为 $\hat\theta$，第二个才是真值 $\theta$。**MSE 是"估计量偏离真值"的平方期望。**

这个恒等式把"总误差"拆成两块，是统计决策论里最常用的分解之一：

$$
\underbrace{E\!\left[(\hat\theta-\theta)^2\right]}_{\textbf{总误差 MSE}}= \underbrace{\operatorname{Var}(\hat\theta)}_{\textbf{抖（精度）}}+ \underbrace{\left[E(\hat\theta)-\theta\right]^2}_{\textbf{偏（准确度）}}
$$

**推导（只有两步，强烈建议自己手写一遍）**：记 $\mu_{\hat\theta} = E(\hat\theta)$，把偏差做个"加一项减一项"：
$$
\hat\theta - \theta = \left(\hat\theta - \mu_{\hat\theta}\right) + \left(\mu_{\hat\theta} - \theta\right)
$$

两边平方后取期望，展开成三项：

$$
E\!\left[(\hat\theta-\theta)^2\right]
= \underbrace{E\!\left[(\hat\theta-\mu_{\hat\theta})^2\right]}_{\operatorname{Var}(\hat\theta)}
+ 2\left(\mu_{\hat\theta}-\theta\right)\underbrace{E\!\left[\hat\theta-\mu_{\hat\theta}\right]}_{=\,0}
+ \underbrace{\left(\mu_{\hat\theta}-\theta\right)^2}_{\text{Bias}^2}
$$

**中间那个交叉项为什么是 0？** 因为 $E\!\left[\hat\theta-\mu_{\hat\theta}\right] = E\hat\theta - \mu_{\hat\theta} = 0$——**括号里的随机部分对它自己的均值取期望，当然是 0**。这一步是整个分解成立的枢纽，也正是"加一项减一项"这个技巧的目的：**把随机波动部分和系统偏差部分拆成互相正交的两块。**

**为什么这个分解重要（这是它真正的价值）**：

- 它说明**"好坏"不能只看偏差**。一个**无偏但方差巨大**的估计量，MSE 可能比一个**稍有偏但方差很小**的估计量还大。
- 所以"**牺牲一点无偏性去换大幅降低方差**"是可以划算的——这正是 **shrinkage / 正则化**（岭回归、James–Stein 估计量、LASSO）这类方法存在的原因。
- 反过来说，**MSE 是把 Bias 和 Var 合成一个数的"单一标尺"**。如果你一定要用一个数评判估计量，MSE 是最自然的选择（代价是它对量纲敏感、且放大了大误差）。

#### 5.4.4 相合性（Consistency）——衡量"样本多了会不会变准"

> ⚠️ **抄录勘误**：你笔记里关于相合性的两行（`When ∀ ≤ 20, θ̂ → P`、`∀ ≥ 30, lim_{n→∞} P{θ²-θ)²`）不是数学上成立的写法，应该是手写体辨认时出的错（$\varepsilon$ 与数字、$\hat\theta$ 与 $\theta$ 在手写时极易混）。我按标准定义还原如下。

$\hat\theta$ 称为 $\theta$ 的**相合估计量（consistent estimator）**，若对**任意** $\varepsilon > 0$，

$$
\lim_{n\to\infty}\Pr\left(\left|\hat\theta - \theta\right| > \varepsilon\right) = 0
$$

等价地写作 $\hat\theta \xrightarrow{\ P\ }\theta$（**依概率收敛于 $\theta$**）。

**逐项解读**：

- **"$\forall\varepsilon>0$"这个量词是关键**。抄录里的 `∀ ≤ 20`、`∀ ≥ 30` 最可能就是 $\forall\varepsilon>0$ 的误认（也可能板书写了 $\varepsilon=0.2$、$\varepsilon=0.3$ 之类作为**举例**）。它的意思是"**不管你把'够接近'的门槛 $\varepsilon$ 定得多苛刻**"——$\varepsilon$ 可以小到 $0.001$，结论依然成立。
- **整个命题的结构**：对任意给定的容差 $\varepsilon$，"$\hat\theta$ 掉出容差之外"这个事件的**概率**，随 $n$ 增大而趋于 0。注意**不是**说"$\hat\theta$ 会等于 $\theta$"（对于连续分布，$P(\hat\theta=\theta)=0$），而是说"**离谱的概率被压没了**"。
- **这完全是第 1 讲 7.1 节大数定律的同一套语言**。把 LLN 用在 $\hat\theta = \bar X$ 上，直接得到 $\bar X \xrightarrow{P}\mu$——**所以 $\bar X$ 是 $\mu$ 的相合估计量**。两讲的符号在这里接上了。

**三个概念的关系（这一层最容易被搞混，务必理清）**：

| | 偏差 / 方差 | 相合性 |
| --- | --- | --- |
| 描述的是 | **固定样本量 $n$ 下**的表现 | **$n\to\infty$ 时**的极限行为 |
| 回答的问题 | "这次（这个 $n$）估得好不好" | "样本多了会不会变好" |

**它们不是并列的三个标准，而是"有限样本"与"渐近"两个层次。**

**两个常见的错误直觉，必须纠正**：

1. **无偏 $\not\Rightarrow$ 相合**。反例：用 $\hat\theta = X_1$（只用第一个观测去估计 $\mu$）。它**无偏**（$E[X_1]=\mu$），但方差恒为 $\sigma^2$、**不随 $n$ 缩小**，丢弃了后面 $n-1$ 个观测的全部信息，所以**永不相合**。
2. **相合 $\not\Rightarrow$ 无偏**。反例：Uniform $[0,\theta]$ 的 $\hat\theta = X_{(n)}$，**有偏**（$\frac{n}{n+1}\theta$）但**相合**（偏差 $\frac{\theta}{n+1}\to0$、方差也 $\to0$）。

**从 MSE 角度看相合性最直观**：由 5.4.3 的分解，如果

$$
\operatorname{Var}(\hat\theta) \to 0 \quad\text{且}\quad \text{Bias}(\hat\theta) \to 0
\qquad\Longrightarrow\qquad \operatorname{MSE}(\hat\theta) \to 0
$$

再由 Chebyshev 不等式（$\Pr(|\hat\theta-\theta|>\varepsilon) \le \dfrac{E[(\hat\theta-\theta)^2]}{\varepsilon^2}$）立刻推出相合性。**所以"渐近无偏 + 方差趋于 0"是相合性的一个充分条件**，这也是证相合性最常用的路子。

---

## 6. 似然函数（Likelihood Function）

### 6.1 定义（讲义第 11 页）

讲义用 Definition 框给出：

> "The likelihood function $L : \Omega \to [0,\infty)$ is equal to the joint density or joint mass function of the observations. $L$ is treated as a function of the parameter $\theta$, that is,"
>
> $$L(\theta) := f(x_1, x_2, \cdots, x_n;\theta) = \prod_{i=1}^{n} f(x_i;\theta).$$

**这个定义里藏着整个 MLE 最核心的思想转变，必须慢慢拆。**

先看公式右边怎么来的。$f(x_1,\ldots,x_n;\theta)$ 是**联合 PMF/PDF**，即"同时观测到 $x_1,\ldots,x_n$ 这组数据的概率（密度）"。因为样本是 **i.i.d.** 的（见 5.2 节），**独立**保证了联合分布等于各个边际分布的乘积：

$$
f(x_1,x_2,\ldots,x_n;\theta) = \prod_{i=1}^{n} f(x_i;\theta) = f(x_1;\theta)\cdot f(x_2;\theta)\cdots f(x_n;\theta)
$$

这里 $\prod$（大写 Pi）是**连乘号**，对应求和号 $\sum$ 的乘法版本，所以 $\prod_{i=1}^n f(x_i;\theta)$ 就是"把 $n$ 个 $f(x_i;\theta)$ 全部乘起来"。**这就是 i.i.d. 假设在推导中的第一次实际用途**——没有独立性，联合分布不能这样拆成乘积。

再看最关键的一点：**注意分号。$f(x_i;\theta)$ 里 $x_i$ 在前、$\theta$ 在后，说明原定义里"$x$ 是自变量，$\theta$ 是固定的参数"。**

**但似然函数做的事是：把两者的角色对调。**

$$
\text{原来：} \quad f(x;\theta) \ \text{—— 固定 } \theta \text{，看 } x \text{ 变化（这是"概率"）}
$$
$$
\text{现在：} \quad L(\theta) \ \text{—— 固定已经观测到的 } x_1,\ldots,x_n \text{，看 } \theta \text{ 变化（这是"似然"）}
$$

**这是一个"概念上的旋转"。** 数据已经拿到手了，是**固定不变的事实**；$\theta$ 才是未知的、要去找的东西。所以把 $x_1,\ldots,x_n$ 当成常数，把 $\theta$ 当成自变量，研究"**当 $\theta$ 取不同值时，我手上这组数据的'可信程度'分别是多少**"。

**符号细节**：$L : \Omega \to [0,\infty)$ 表示 $L$ 是从**参数空间 $\Omega$**（自变量范围）映射到**非负实数**（因为概率密度不能为负）的函数。所以 $L$ 的定义域是 $\Omega$，**这也正是为什么 $\Omega$ 必须明确写出来**：$L$ 只在 $\Omega$ 上有定义，最大化时也只能在 $\Omega$ 里找。

**必须澄清的一个巨大误解（这是本页最容易被曲解的地方）**：

$L(\theta)$ 的值**不是**"$\theta$ 为真的概率"，也**不是**一个概率。$\theta$ 在频率派（frequentist）框架下**是固定的未知常数，不是随机变量**，所以"$P(\theta = \theta_0)$"这种说法本身就没有定义。$L(\theta)$ 的正确读法是：

> **"在参数取值为 $\theta$ 的那些总体里，观测到我手上这组数据 $x_1,\ldots,x_n$ 的可能性（plausibility）有多大。"**

$L(\theta)$ 更大的意思是"$\theta$ 这个值跟我看到的数据**更相容（more compatible）**"。这就是为什么我们最终要挑让 $L$ 最大的那个 $\theta$——**因为它让"我实际看到的东西"看起来最不意外。**

顺带一个细节：$L$ 的取值可以大于 1。概率密度函数（PDF）的取值本来就可以大于 1（只要积分为 1），而 $L$ 是 $n$ 个密度的乘积，量级可能极大或极小——**这也是为什么下一个小节要取对数**。

### 6.2 对数似然（Log-likelihood，讲义第 11 页下半）

> "The log-likelihood function is defined by $\ell(\theta) := \ln L(\theta)$."

- $\ln$ 是**自然对数**（以 $e$ 为底）。
- 记号：$\ell(\theta)$（手写体的 L，读作 "ell"）。
- 展开写成完整形式：

$$
\ell(\theta) = \ln\left[\prod_{i=1}^{n} f(x_i;\theta)\right] = \sum_{i=1}^{n} \ln f(x_i;\theta)
$$

**这一步用了对数的核心性质**：$\ln(ab) = \ln a + \ln b$。所以**连乘变成了求和**：

$$
\ln\left(f(x_1;\theta) f(x_2;\theta)\cdots f(x_n;\theta)\right) = \ln f(x_1;\theta) + \ln f(x_2;\theta) + \cdots + \ln f(x_n;\theta)
$$

**为什么要把连乘转成求和？两个理由，都很实际：**

**理由一（数学上）：求导变得容易得多。** 求 $\prod f(x_i;\theta)$ 的导数要用乘法法则一层层展开，$n$ 项就要展开 $n$ 次；而 $\sum \ln f(x_i;\theta)$ 的导数就是**逐项求导再相加**，因为求导对加法是线性的：

$$
\frac{d}{d\theta}\ell(\theta) = \sum_{i=1}^{n} \frac{d}{d\theta}\ln f(x_i;\theta) = \sum_{i=1}^{n}\frac{f'(x_i;\theta)}{f(x_i;\theta)}
$$

（最后一步用了链式法则：$(\ln u)' = u'/u$。）**这个"逐项相加"的结构，直接导致了后面 MLE 求解具有极强的可操作性。**

**理由二（数值上）：避免浮点下溢。** 概率密度通常在 $0$ 到 $1$ 之间，$n$ 个小于 1 的数连乘会**指数级地趋于零**。比如 $n = 1000$、每个 $f \approx 0.01$，乘积就是 $10^{-2000}$——**这远远超出了双精度浮点数的最小范围（约 $10^{-308}$），会直接下溢成 0**，计算机就完全无法区分"非常小"和"零"，任何比较都失去意义。而取对数后，$10^{-2000}$ 变成 $-4605$，$10^{-2001}$ 变成 $-4608$，**差别被完整保留在可表示的范围内**。这是所有实际 MLE 实现都跑在 log 尺度上的原因。

### 6.3 黑板补充：似然函数的两分支正式写法

课堂板书把 6.1 节的定义写得更完整了一步——**因为"密度"这个词在离散和连续两种情形下对应不同的函数**，所以 $L$ 的定义必须分两个分支。板书写的是：

$$
L(\theta) = \begin{cases}
P(X_1 = x_1,\ \ldots,\ X_n = x_n;\ \theta) \overset{iid}{=} \displaystyle\prod_{i=1}^{n} P(X_i = x_i;\ \theta), & \text{离散情形（离散型 $X$）} \\[14pt]
f(x_1,\ \ldots,\ x_n;\ \theta) \overset{iid}{=} \displaystyle\prod_{i=1}^{n} f(x_i;\ \theta), & \text{连续情形（连续型 $X$）}
\end{cases}
$$

**这个分支写法要理解三点：**

- **上分支用的是 $P$（概率质量函数）**，因为它算的是"$X_i$ 恰好等于某个具体值 $x_i$"的**概率**。板书里特意把 $X_i = x_i$ 写全（$P(X_1 = x_1, \ldots, X_n = x_n;\theta)$），强调了这是"**取到具体点值**"的情形。离散型随机变量在某一点上确实有正概率，所以这个写法有意义。
- **下分支用的是小写 $f$（概率密度函数）**，因为它算的是"密度"。**关键区别**：连续型随机变量取到任一**确切点值**的概率是 0，所以 $P(X_i = x_i)$ 在连续情形下恒为 0、毫无信息量；有信息量的是**密度** $f(x_i;\theta)$。这也解释了为什么第 1 讲要把 PMF 和 PDF 分成两个概念——它们在似然函数里**必须区别对待**。
- **中间的 $\overset{iid}{=}$ 是理解整个定义的关键**。它表示等号右边与左边相等**是因为 i.i.d. 假设**：
  - **"i"（independent，独立）** 提供了"**联合 = 边缘之积**"这一步拆分，也就是从 $P(X_1=x_1,\ldots,X_n=x_n)$ 变成 $\prod_i P(X_i=x_i)$；
  - **"d"（identically distributed，同分布）** 提供了"**所有因子共用同一条曲线、同一个参数 $\theta$**"这一条件，也就是每个因子都写成 $P(X_i = x_i;\theta)$ 而**不是** $P(X_i = x_i;\theta_i)$（如果分布不同，就得给每个 $i$ 配一个不同的参数，那就没法只估一个 $\theta$ 了）。
  
  **所以板书这个 $\overset{iid}{=}$ 符号，实际上是在提醒：似然函数里那个漂亮的连乘 $\prod$ 是"买"来的，代价是 i.i.d. 假设。** 一旦独立性或同分布不成立（时间序列自相关、分组异质），这个乘积形式就崩了。这也是 5.2 节强调 i.i.d. 的具体原因。

**板书左边缘还写了两个字**："**unbiased**"（无偏）和 "**consistency**"（相合性），并画了一个箭头指向 $L(\theta)$。这是在预告**下一讲的主题**：本讲只解决了"如何构造估计量"，而**这个估计量好不好**（是否无偏、是否相合、方差多大）要留到下一讲评价。板书的这个箭头等于告诉你：**$L(\theta)$ 是下一讲所有评价指标的出发点。**

（板书上另有一处 "positive / negative" 的标注，是邻接内容的标题，与本节无关，此处不展开。）

---

## 7. 最大似然估计（Maximum Likelihood Estimation, MLE）

### 7.1 定义（讲义第 12 页）

> "The maximum likelihood estimator (MLE), denoted by $\hat\theta$, is the value of $\theta$ that maximizes $L(\theta)$."

$$
\hat\theta = \arg\max_{\theta \in \Omega} L(\theta)
$$

- **$\arg\max$** 的意思是"**使后面那个式子取得最大值的自变量**"。要特别注意 $\max$ 和 $\arg\max$ 的区别：$\max_\theta L(\theta)$ 返回的是**最大值本身**（一个数，比如 $0.37$），而 $\arg\max_\theta L(\theta)$ 返回的是**达到最大值的那个 $\theta$**（比如 $p = 0.3$）。我们要的是后者。
- 定义域写了 $\theta \in \Omega$，**提醒最大化必须在参数空间内部或其边界上进行**。

> "To derive the expression of MLE, it is often easier to maximize $\ell(\theta)$ rather than to maximize $L(\theta)$."

> "Since the natural logarithm function is a strictly increasing function, the resulting maximizer $\hat\theta$ from maximizing $\ell(\theta)$ is the same as that of $L(\theta)$."

**为什么可以放心地换成最大化 $\ell$ 而不改变答案？** 因为 $\ln$ 是**严格递增函数（strictly increasing function）**：对任意 $a < b$，都有 $\ln a < \ln b$（只要 $a,b>0$，而 $L \ge 0$ 满足条件）。

所以"$L$ 在 $\theta^*$ 处最大"和"$\ln L$ 在 $\theta^*$ 处最大"是**完全等价的命题**。用图来理解：把 $L$ 的曲线做一次单调的纵向拉伸/压缩（对数变换恰好是"压缩大值、拉伸小值"的变换），曲线的**形状变了、峰的高度变了，但峰所在的位置一动不动**。而我们要的只是"峰的位置"（自变量），不是"峰有多高"（函数值），所以单调变换是**完全无害**的。

**这个论证非常重要，因为它是一个更普遍原则的特例**：**任何严格单调变换都不改变极值点的位置。** 后面学置信区间、假设检验时会遇到别的单调变换（比如平方根、Fisher z 变换），都是同一个道理。

### 7.2 求解 MLE 的通用套路：板书版"①②③"

讲义第 13–16 页的四个例子都是"动手算"，但**没有把流程本身总结成一条可复用的配方**。课堂板书补上了这一块——板书专门画了一个框，标题是 "Calculation of MLE"，把整个求解过程压缩成三步：

板书原文：

$$
\textbf{Calculation of MLE:}\quad
\begin{cases}
\text{\textcircled{1}} & \text{formulate } L(\theta) \\[8pt]
\text{\textcircled{2}} & \dfrac{\partial \ell(\theta)}{\partial \theta} = 0 \ \Longrightarrow\ \hat\theta \\[8pt]
\text{\textcircled{3}} & \left.-\dfrac{\partial^2 \ell(\theta)}{\partial \theta^2}\right|_{\theta = \hat\theta} > 0 \ \Longrightarrow\ \hat\theta \text{ is MLE}
\end{cases}
$$

**逐条解释：**

**① formulate $L(\theta)$（写出似然函数）**：用 6.1 / 6.3 节的两分支公式，把 $n$ 个 PMF 或 PDF 连乘起来：

$$
L(\theta) = \prod_{i=1}^{n} f(x_i;\theta)
$$

操作要点是**把连乘用指数法则压缩**（$a^m a^k = a^{m+k}$、$(a^m)^n = a^{mn}$），把散落在各个因子里的同一个底数**合并成一个幂**，同时把常系数（如 $1/x_i!$、$1/\sqrt{2\pi}$ 等）单独提出来。这一步做干净了，后面取对数才不会乱。

**② $\dfrac{\partial \ell(\theta)}{\partial \theta} = 0 \Rightarrow \hat\theta$（解得分方程）**：

- 板书用的是**偏导符号 $\partial$** 而不是 $\frac{d}{d\theta}$。这对**多参数**情形是必要的准备：当 $\theta = (\theta_1,\theta_2,\ldots,\theta_k)$ 是向量时，要对**每一个分量**分别求偏导，得到 $k$ 个方程联立。单参数时 $\partial$ 和 $d$ 没有区别。
- 这个方程在板书里被称为 **score function 的零点**：导数 $\frac{\partial \ell(\theta)}{\partial\theta}$ 本身叫**得分函数（score function）**，令它为零就是在找"得分为零"的点。板书在 7.3 节的 Bernoulli 推导里专门用箭头把这几个字标出来了。
- 这一步给出的是**驻点（stationary point）**，**还不一定是最大值点**。这就引出了第③步。

**③ $-\left.\dfrac{\partial^2 \ell(\theta)}{\partial \theta^2}\right|_{\theta = \hat\theta} > 0 \Rightarrow \hat\theta$ is MLE（二阶条件）**：

**这是板书的写法最值得学习的地方——它把二阶条件写成"负的二阶导大于零"**，而不是我原稿里写的"$\ell''<0$"。两种写法完全等价：

$$
-\left.\frac{\partial^2 \ell(\theta)}{\partial \theta^2}\right|_{\theta=\hat\theta} > 0 \quad \Longleftrightarrow \quad \left.\frac{\partial^2 \ell(\theta)}{\partial \theta^2}\right|_{\theta=\hat\theta} < 0
$$

就是把不等式两边同乘 $-1$ 再翻转方向。**为什么要刻意写成 $-\ell'' > 0$？** 因为这样写出来的形式**与"信息量"的定义一致**——统计学里把 $-E\left[\ell''(\theta)\right]$ 叫做 **Fisher 信息量（Fisher information）**，它度量"数据里关于 $\theta$ 有多少信息"。$\ell'' < 0$（即 $-\ell'' > 0$）意味着 $\ell$ 在这一点是**凹的（concave）**，曲线像个倒扣的碗，驻点必然是（局部）最大值。

**几何直觉**：$\ell'(\hat\theta)=0$ 只说明"曲线在这里是平的"——可平坦点可能是山顶（最大值）、谷底（最小值）或山坡上的一个平台（拐点）。$\ell''(\hat\theta)<0$ 则进一步说明"曲线在这里向下弯曲"，即**这是个山顶**。两步合起来才叫"确认 MLE"。

**板书的第③步还揭示了一个容易被忽略的要点**：$\hat\theta$ **不是**"$\ell'$ 的任意零点"，而是"$\ell'$ 的零点**且** $\ell''<0$ 的那一个"。**当得分方程有多个解时，必须逐一检查二阶条件，挑真正是最大值的那一个。** 讲义四道例题都恰好只有一个解，所以没暴露出这个问题，但一般情形下它是真实存在的。

**板书还顺手写下了多参数的推广**（板书上另有一小行）：当 $\theta$ 是向量时，二阶对象不再是标量而是**矩阵**：

$$
-\frac{\partial^2 \ell(\theta)}{\partial \theta\, \partial \theta^{\mathsf{T}}}
$$

这是 $\ell$ 的**海森矩阵（Hessian matrix）**取负号，第③步的条件相应变成"**该矩阵负定（negative definite）**"。向量情形在后面的多元参数估计（例如同时估正态的 $\mu$ 和 $\sigma^2$）会用到。

**板书还有一处记号约定**：框的左上方写了

$$
\ln L(\theta) \triangleq \ell(\theta)
$$

$\triangleq$（等号上方有三角形）是"**定义为（is defined as）**"的标准记号。板书特意标出它，是为了说明 $\ell$ 只是 $\ln L$ 的一个**缩写**，不是什么新东西。同一块板上 7.3 节的 Poisson 推导里，$\log$ 的两个指数项旁还分别标注了 **"(ln)"** 和 **"(e)"**——前者提醒"这里的 $\log$ 就是自然对数 $\ln$"，后者提醒"这一项是从 $e$ 的指数上取对数得来的"。**这个提醒很实用：统计学文献里 $\log$ 几乎总是指自然对数，但在不同教材里偶尔会指以 2 或 10 为底的对数，看到时先确认约定。**

**最后，板书的①②③并非万能——这是必须配套记住的例外**（讲义用 7.6 节的 Uniform 例子专门演示）：当 $\Omega$ 是有界区间、或者密度的**支撑集（support，即 $f(x) > 0$ 的 $x$ 范围）依赖于 $\theta$** 时，$\ell$ 可能在某处不可导、或者单调递减，此时**最大值会出现在参数空间的边界上，第②步的方程根本无解或解不在 $\Omega$ 内**，必须回到"直接比较 $L(\theta)$ 在各段上的取值"的做法。这就是 7.6 节的情况，也是讲义特意安排那个例子的用意。

### 7.3 例 1：Bernoulli($p$)（讲义第 13 页）

**题目**：$X_1, \ldots, X_n \sim \text{Bernoulli}(p)$，PMF 是

$$
f(x;p) = p^x(1-p)^{1-x}, \quad x \in \{0,1\}, \quad 0 \le p \le 1
$$

参数空间 $\Omega = \{p : 0 \le p \le 1\}$。注意这里写的是**闭区间** $[0,1]$（端点可以取到），而 **$\hat p = \bar X$ 恰好能取到 0 和 1**，所以闭区间是必要的（见下面"边界情形"的讨论）。

**先说模型本身**：Bernoulli 分布描述"一次只有两个结果的试验"（抛硬币：正面 1 / 反面 0）。$p = P(X=1)$ 是"成功"的概率。当 $x=1$ 时 $f = p^1(1-p)^0 = p$；当 $x=0$ 时 $f = p^0(1-p)^1 = 1-p$。**这个 $x$ 在指数上的巧妙写法，让一个公式同时覆盖两种情形**——这是统计学里极常见的技巧（叫 indicator 写法），要能一眼看懂。

**第一步，写似然**：

$$
L(p) = \prod_{i=1}^{n} f(x_i;p) = \prod_{i=1}^{n} p^{x_i}(1-p)^{1-x_i} = p^{\sum_{i=1}^{n} x_i}(1-p)^{n-\sum_{i=1}^{n} x_i}
$$

**中间那一步值得拆开说明**，因为它是最常卡住的地方：连乘时，每个因子里都有 $p^{x_i}$ 和 $(1-p)^{1-x_i}$。因为**乘法交换律**，可以把所有 $p$ 的幂次挪到一起、所有 $(1-p)$ 的幂次挪到一起；又因为 $a^m \cdot a^k = a^{m+k}$，**指数相加**：

$$
\prod_i p^{x_i} = p^{x_1 + x_2 + \cdots + x_n} = p^{\sum x_i}
$$

对于 $(1-p)$ 部分：每个因子的指数是 $1-x_i$，加起来是

$$
\sum_{i=1}^{n}(1-x_i) = n - \sum_{i=1}^{n}x_i
$$

所以得到 $L(p) = p^{\sum x_i}(1-p)^{n - \sum x_i}$。**这里只有两个"统计量"在起作用：观测到的 1 的个数 $\sum x_i$ 和 0 的个数 $n - \sum x_i$。**

**第二步，取对数**（用 $\ln(a^m) = m\ln a$，再用 $\ln(ab) = \ln a+\ln b$）：

$$
\ell(p) = \left(\sum_{i=1}^{n} x_i\right)\ln p + \left(n - \sum_{i=1}^{n} x_i\right)\ln(1-p)
$$

**第三步，求导并令其为零**：

$$
\ell'(p) = \frac{\sum x_i}{p} - \frac{n - \sum x_i}{1-p} = 0
$$

（对第一项用 $\frac{d}{dp}\ln p = \frac{1}{p}$；对第二项用链式法则，注意 $\frac{d}{dp}\ln(1-p) = \frac{-1}{1-p}$，**这个负号是最容易漏的**。）

解这个方程：

$$
(1-p)\sum x_i = p\left(n - \sum x_i\right)
$$
$$
\sum x_i - p\sum x_i = np - p\sum x_i
$$
$$
\sum x_i = np
$$
$$
\boxed{\hat p = \frac{1}{n}\sum_{i=1}^{n} x_i = \bar x}
$$

（注意 $-p\sum x_i$ 在两边**恰好抵消**，这是一次幸运的化简。**从这个方程可以反推出一个重要的直觉：MLE 让"理论上的期望成功次数 $np$"等于"观测到的成功次数 $\sum x_i$"。** 这是一个很好记的判据——**对 Bernoulli/Poisson/Exponential 这类单参数指数族，MLE 的方程本质上都是"理论均值 = 样本均值"。**）

**第四步，验证是极大值**：

$$
\ell''(p) = -\frac{\sum x_i}{p^2} - \frac{n-\sum x_i}{(1-p)^2} < 0 \quad (\text{因为 } \sum x_i \ge 0,\ n-\sum x_i \ge 0)
$$

二阶导数在 $(0,1)$ 内**恒为负**，所以 $\ell$ 是**严格凹函数（strictly concave）**，驻点就是**唯一的全局最大值点**。这个验证很强，不是"局部极大"而是"全局最大"。

**结果解读**：$\hat p = \bar X$ 就是**样本中 1 的比例**。教室里最熟悉的例子：抛 100 次硬币得到 60 个正面，则 $\hat p = 0.6$。这个结果和直觉完全一致——**"有多少比例是成功，就估成功率是多少"**。**MLE 在这里的作用不是推翻直觉，而是告诉你这个直觉做法在数学上是"最优"的（这是第 8 节定理要说的）。**

**边界情形（讲义未展开，我补充）**：如果**所有** $x_i = 0$（一次都没成功），则 $\ell(p) = n\ln(1-p)$，这是关于 $p$ 的严格递减函数，最大值在 $p = 0$ 处取得；公式 $\hat p = \bar x = 0$ 仍然给出正确答案。对称地，全部 $x_i=1$ 时 $\hat p = 1$。**这就是为什么参数空间要写成闭区间 $0\le p\le 1$**——极值真的会在端点取到。求导法在这里依然工作（因为 $\ell'(0^+)$ 和 $\ell'(1^-)$ 可以讨论），但如果换成一个"$\ell$ 在端点不连续"的问题，就必须单独讨论边界。

#### 7.3.1 黑板补充：用样本均值 $\bar x$ 压缩的写法，以及"score function"一词

课堂教学时把上面这套推导**改用样本均值 $\bar x$ 重写了一遍**，形式更紧凑，也把"得分函数"这个名字落到了实处：

板书写的是：

$$
\ell(p) = n\bar x \log p + n(1-\bar x)\log(1-p)
$$

**这个写法是上一节 $\ell(p) = \left(\sum x_i\right)\ln p + \left(n-\sum x_i\right)\ln(1-p)$ 的等价改写**，只是把 $\sum_{i=1}^{n}x_i$ 用 $n\bar x$ 替换、把 $n-\sum x_i$ 用 $n(1-\bar x)$ 替换：

$$
\sum_{i=1}^{n}x_i = n\bar x, \qquad n - \sum_{i=1}^{n}x_i = n\left(1 - \bar x\right)
$$

改写的好处是**把 $\ell$ 直接写成 $\bar x$ 的函数**，一眼就能看出"$\ell$ 只通过 $\bar x$ 这一个数依赖于全部数据"。这个现象有专门的名字：$\bar x$（或者说 $\sum x_i$）是 $p$ 的**充分统计量（sufficient statistic）**——**它把 $n$ 个数里关于 $p$ 的信息全部浓缩成了一个数**，其他的信息（比如各个 $x_i$ 的排列顺序）对估计 $p$ 毫无用处。本讲不考这个概念，但它是下一阶段（充分性、因子分解定理）的核心，先留个印象。

板书的求导两行是：

$$
\frac{\partial \ell(p)}{\partial p} = \frac{n\bar x}{p} - \frac{n(1-\bar x)}{1-p},
\qquad
\frac{\partial^2 \ell(p)}{\partial p^2} = -\frac{n\bar x}{p^2} - \frac{n(1-\bar x)}{(1-p)^2}
$$

**注意这两行里的负号来源，这是本页最容易出错的地方**：

- $\ell(p)$ 的第二项是 $+n(1-\bar x)\log(1-p)$，底数是 **$(1-p)$**。对 $p$ 求导时，$\log(1-p)$ 的导数是 $\frac{-1}{1-p}$（链式法则：外层 $\frac{d}{du}\log u = \frac{1}{u}$，内层 $\frac{d}{dp}(1-p) = -1$）。**所以一阶导里的负号来自"内层的 $-1$"，不是来自 $\ell$ 本身的减号。**
- 二阶导两项都是**负的**：第一项 $\frac{n\bar x}{p}$ 求导得 $-\frac{n\bar x}{p^2}$；第二项 $-\frac{n(1-\bar x)}{1-p}$ 求导，分母 $(1-p)$ 的导数是 $-1$，负负得正……等一下，仔细算：$\frac{d}{dp}\left[-\frac{n(1-\bar x)}{1-p}\right] = -n(1-\bar x)\cdot\frac{d}{dp}(1-p)^{-1} = -n(1-\bar x)\cdot\left(+(1-p)^{-2}\right)$，因为 $\frac{d}{du}u^{-1} = -u^{-2}$ 再乘内层导数 $-1$，得 $+u^{-2}$。所以结果是 $-\frac{n(1-\bar x)}{(1-p)^2}$。**与板书一致。**
- 二阶导**两项都非负号，恒小于 0**（因为 $\bar x \in [0,1]$、$p\in(0,1)$），所以 $\ell$ 严格凹，第③步自动成立。

然后板书令一阶导为零：

$$
\frac{\partial \ell(p)}{\partial p} = 0 \ \Longrightarrow\ \hat p = \bar x
$$

并在 $\frac{\partial \ell(p)}{\partial p}$ 旁边**用箭头标了 "score function"**，然后写下二阶条件：

$$
\left.-\frac{\partial^2 \ell(p)}{\partial p^2}\right|_{p=\bar x} > 0
$$

**"score function" 这个词的用法值得专门记一下**：它指的是**对数似然的一阶导数 $\frac{\partial \ell(\theta)}{\partial\theta}$ 这个函数本身**（不是它的零点、也不是 $\hat\theta$）。它的名字来自"score"，可以直译为"（似然曲线的）坡度"。这个量在统计学的后续课程里是个主角——**令 score 为零得 MLE，求 score 的方差得 Fisher 信息量，score 的渐近正态性直接给出 MLE 的渐近分布**（也就能算置信区间和做检验）。本讲只用到第一件事。

> **一处关于板书符号歧义的说明**：板书上 $\ell(p)$ 那一行的第二项符号与紧接着的一阶导 $\frac{n\bar x}{p} - \frac{n(1-\bar x)}{1-p}$ **不能同时成立**——若 $\ell$ 里真是减号，一阶导第二项就该是加号。由于一阶导、二阶导两行都与"**加号**"版本完全吻合（一阶导的那个负号来自 $\log(1-p)$ 的链式法则），且手写体的 $+$ 与 $-$ 极易混淆，本笔记按**数学上自洽的加号版本**记录，即 $\ell(p) = n\bar x\log p + n(1-\bar x)\log(1-p)$。同理，第二项的括号按 $\log(1-p)$ 而非 $\log(1+p)$ 记录——只有 $\log(1-p)$ 才对应 Bernoulli 的 $1-p$，也才能导出那个 $-\frac{n(1-\bar x)}{1-p}$。**如果日后核对发现板书确实是减号，那它就是一处笔误，本节按加号理解即可。**

> **✅ 交叉验证（2026-09-15，对照课堂抄录笔记）**：课堂抄录的笔记里，这一行确实写成了**减号**：
> $$u(p) = n\bar x\ln p - n(1-\bar x)\ln(1-p), \qquad \underbrace{U(p)}_{\text{score function}} = \frac{\partial\ell(p)}{\partial p} = 0 \Rightarrow \hat p = \bar x$$
> 这就**证实了上面的推断：板书是减号，而这处减号是笔误。** 理由是它可以被立刻验算推翻：
> 1. **若 $\ell(p) = n\bar x\ln p - n(1-\bar x)\ln(1-p)$**，则求导时第二项是 $-\ln(1-p)$，其导数为 $-\left(\frac{-1}{1-p}\right) = +\frac{1}{1-p}$，于是
>    $$\ell'(p) = \frac{n\bar x}{p} + \frac{n(1-\bar x)}{1-p}$$
>    **这个式子里的两项在 $p\in(0,1)$ 时恒为正，永远不会等于 0**——根本解不出 $\hat p = \bar x$，第②步直接卡死。
> 2. **只有加号版本** $\ell(p) = n\bar x\ln p + n(1-\bar x)\ln(1-p)$ 才能给出
>    $$\ell'(p) = \frac{n\bar x}{p} - \frac{n(1-\bar x)}{1-p} = 0 \ \Longrightarrow\ \hat p = \bar x$$
>    与板书下方的一阶导、二阶导**完全吻合**。
>
> **结论：板书漏写/误写了符号，本笔记按加号版本（数学正确版）记录。** 抄录笔记时若照抄了减号，做题会卡在第②步——这正好是一个"**抄板书要当场验算**"的实例：**只要把 $\hat p=\bar x$ 代回去检查一下等式是否真的成立，符号错误当场就会暴露。**
>
> 顺带说明抄录里的两处记号：`u(p)` 与 `U(p)` 是同一个东西的两种大小写写法（$\ell(p)$）；"score function" 的箭头标注位置与本笔记的理解一致——**它指的是 $\frac{\partial\ell}{\partial p}$ 这个函数本身，而不是 $\hat p$**（§7.2 与本节上文已详细讨论）。

### 7.4 例 2：Exponential($\theta$)（讲义第 14 页）

**题目**：$X_1,\ldots,X_n$ i.i.d. 服从参数为 $\theta$ 的指数分布：

$$
f(x;\theta) = \frac{1}{\theta}e^{-x/\theta}, \quad 0 < x < \infty, \quad \theta \in (0,\infty)
$$

**先认清 $\theta$ 是什么**（这一步至关重要，否则会算完不知道自己估了什么）：指数分布有两种常见参数化——

- **尺度参数化（scale parameterization）**：$f(x;\theta) = \frac{1}{\theta}e^{-x/\theta}$，此时 $E[X] = \theta$，$\mathrm{Var}(X) = \theta^2$。**本讲义用的是这一种。**
- **速率参数化（rate parameterization）**：$f(x;\lambda) = \lambda e^{-\lambda x}$，此时 $E[X] = 1/\lambda$，$\mathrm{Var}(X) = 1/\lambda^2$。其中 $\lambda = 1/\theta$。

（第 1 讲笔记第 5.1 节学过指数分布，讲的就是 $\theta$ 是尺度参数、"$\theta$ = 平均等待时间"这个理解。）**所以本讲的 $\theta$ 就是这道题的"平均等待时间"，与第 1 讲的记号一致。** 做题时先看讲义给的 $f$ 长什么样，再决定 $\theta$ 是均值还是速率——**这是指数分布题目最常见的坑。**

**第一步，写似然**：

$$
L(\theta) = \prod_{i=1}^{n}\frac{1}{\theta}e^{-x_i/\theta} = \theta^{-n}\exp\left(-\frac{\sum_{i=1}^{n}x_i}{\theta}\right)
$$

（推导：$\frac{1}{\theta}$ 连乘 $n$ 次得 $\theta^{-n}$；指数部分 $e^{-x_1/\theta}\cdots e^{-x_n/\theta} = e^{-(x_1+\cdots+x_n)/\theta}$，用了 $e^a e^b = e^{a+b}$。讲义把 $1/\theta$ 写成 $\theta^{-n}$ 的形式，**是为了后面求导时能直接用幂函数法则**。）

**第二步，取对数**（用 $\ln(\theta^{-n}) = -n\ln\theta$ 和 $\ln e^u = u$）：

$$
\ell(\theta) = -n\ln\theta - \frac{1}{\theta}\sum_{i=1}^{n}x_i
$$

**第二步的化简特别干净**：因为指数上恰好是 $e^{\ln}$ 的逆运算，$\ln$ 直接把指数"剥掉"了，所以 $\ell$ 里完全不含 $e$。**这是指数族分布取对数后的普遍特征——$\ell$ 变成简单的代数式。**

**第三步，求导并令零**：

$$
\ell'(\theta) = -\frac{n}{\theta} + \frac{1}{\theta^2}\sum_{i=1}^{n}x_i = 0
$$

（第一项的导数是 $-\frac{n}{\theta}$；第二项 $\frac{d}{d\theta}\left[-\theta^{-1}\sum x_i\right] = +\theta^{-2}\sum x_i$，**注意 $\theta$ 在分母上，求导后符号变正、幂次从 $-1$ 变 $-2$，这个符号容易搞错**。）

两边乘 $\theta^2$：

$$
-n\theta + \sum_{i=1}^{n}x_i = 0 \quad \Longrightarrow \quad \boxed{\hat\theta = \frac{1}{n}\sum_{i=1}^{n}X_i = \bar X}
$$

**第四步，验证二阶导**：

$$
\ell''(\theta) = \frac{n}{\theta^2} - \frac{2\sum x_i}{\theta^3}
$$

在 $\theta = \bar x = \frac{\sum x_i}{n}$ 处代入：

$$
\ell''(\bar x) = \frac{n}{\bar x^2} - \frac{2n\bar x}{\bar x^3} = \frac{n}{\bar x^2} - \frac{2n}{\bar x^2} = -\frac{n}{\bar x^2} < 0 \quad \checkmark
$$

确认是极大值，且 $\ell$ 在 $(0,\infty)$ 上凹，所以是全局最大。

**结果解读**：**$\hat\theta = \bar X$，即"平均等待时间"的 MLE 就是样本均值。** 这个结果非常自然：$\theta$ 本身定义为 $E[X]$，而我们用样本均值去估总体均值。**但请注意，这个"自然"不是天上掉下来的，而是从似然最大化一步步推出来的。** 后面学矩估计法（Method of Moments）会发现矩估计给出同样的结果，但**两个方法在别的分布上会给出不同的答案**，那时才知道 MLE 的独特价值。

**讲义没写但值得知道的一点（MLE 的不变性，Invariance Property）**：如果改成速率参数化，$\lambda = 1/\theta$，那么由 MLE 的**不变性**，$\hat\lambda = 1/\hat\theta = 1/\bar X$。也就是说**换了参数化方式，不必重新做一遍最大化，直接把 $\hat\theta$ 代入变换函数即可**。这个性质在后面的课程里（比如正态中估计 $\sigma$ 而不是 $\sigma^2$）会反复用到。

#### 7.4.1 黑板补注：被圈出来的 $\lambda e^{-\lambda x}$

课堂板书在 Poisson 的推导结果旁**单独圈出了**一个式子：

$$
\lambda e^{-\lambda x}, \qquad x > 0,\ \lambda > 0
$$

**这个式子就是指数分布**，而且是**速率参数化（rate parameterization）** 的那一版——正好和本节的主题对上。**板书把它圈出来，等于是在提醒：指数分布有两种面貌，别搞混。** 两种写法的对照如下：

| | 尺度参数化（scale） | 速率参数化（rate） |
| --- | --- | --- |
| 密度 | $f(x;\theta) = \dfrac{1}{\theta}e^{-x/\theta}$（本节讲义用的） | $f(x;\lambda) = \lambda e^{-\lambda x}$（板书圈出的） |
| 参数含义 | 平均等待时间 | 单位时间内的平均**事件发生率** |
| 均值 $E[X]$ | $\theta$ | $1/\lambda$ |
| 方差 | $\theta^2$ | $1/\lambda^2$ |
| MLE | $\hat\theta = \bar X$（7.4 节已推出） | $\hat\lambda = \dfrac{1}{\bar X}$（由不变性直接得到） |

**两者的换算关系就是 $\lambda = 1/\theta$**，所以是**同一个分布族，只是一个参数换成它的倒数**。**做题时务必先看题目给的是哪个形式**——这是指数分布题目最经典的"坑"，因为"$\theta$ 变大"和"$\lambda$ 变大"对分布的影响**方向相反**（前者让等待更久，后者让事件更频繁）。

**为什么板书要在这里圈它？** 我给出两种可能，并标出把握程度：

- **（把握较大）它就是上面那张表里的速率版密度**，被圈出来是为了强调"同一个分布有不同参数化，换参数化时 MLE 跟着换（靠不变性），不必重推"。
- **（我的推断，建议对照课堂确认）** 更可能是**与紧邻的 Poisson 例题配套的一个注记**：如果事件按照参数为 $\lambda$ 的 **Poisson 过程** 到达，那么**相邻两次事件之间的等待时间服从速率 $\lambda$ 的指数分布，密度正是 $\lambda e^{-\lambda x}$**，平均等待时间 $1/\lambda$。这条"**Poisson 计数 ↔ 指数等待**"的对应关系是排队论和生存分析的基础，也解释了为什么第 1 讲笔记里会把 Poisson 和 Exponential 放在一起讲（两个分布的支撑、形态、参数含义都成对出现）。

**这条对应关系为什么成立（给想深究的同学）**：设 $T$ 为等待下一次事件的时间，则"$T > t$"意味着"在长度 $t$ 的时间窗内**一次事件都没发生**"。而 Poisson $(\lambda)$ 过程在长度 $t$ 内的发生次数服从 Poisson $(\lambda t)$，所以

$$
P(T > t) = P\big(\text{Poisson}(\lambda t) \text{ 取值为 } 0\big) = e^{-\lambda t}
$$

（用了 4.1 节讲义里 $P(X=k)=\frac{e^{-\lambda}\lambda^k}{k!}$ 取 $k=0$、把 $\lambda t$ 代入 $\lambda$ 位置。）于是

$$
F_T(t) = 1 - e^{-\lambda t}, \qquad f_T(t) = F_T'(t) = \lambda e^{-\lambda t}
$$

**正好就是板书圈出的那个式子。** 也就是说，**指数分布的密度可以从 Poisson 分布"推导"出来**——这算是对板书那个圈的一个侧面印证：它出现在 Poisson 例题旁边并非偶然。

### 7.5 例 3：Geometric($p$)（讲义第 15 页）

**题目**：$X_1,\ldots,X_n$ i.i.d. 服从 PMF 为

$$
f(x;p) = (1-p)^{x-1}p, \quad x = 1, 2, \ldots, \quad p \in (0,1)
$$

的几何分布。

**先说模型的含义**：这个形式的几何分布描述"**独立重复试验中，第一次成功所需的总试验次数**"。比如掷硬币直到第一次出现正面，掷了 $x$ 次，则 $x$ 服从这个分布（前 $x-1$ 次都失败、概率各 $1-p$；第 $x$ 次成功、概率 $p$）。$E[X] = 1/p$——**注意这是个"次数"的量，所以期望是 $1/p$ 而不是 $p$，这一点在解读答案时必须清楚。**

（教材里几何分布还有一种"失败次数"的版本 $f(x;p) = (1-p)^x p,\ x=0,1,\ldots$，那时 $E[X] = (1-p)/p$。**同一名字下有不同定义，做题一定以讲义给的公式为准。**）

**第一步，写似然**：

$$
L(p) = \prod_{i=1}^{n}(1-p)^{x_i-1}p = p^{n}(1-p)^{\sum_{i=1}^{n}x_i - n}
$$

（$p$ 连乘 $n$ 次得 $p^n$；$(1-p)$ 的指数是 $\sum_i (x_i-1) = \sum_i x_i - n$。）

**第二步，取对数**：

$$
\ell(p) = n\ln p + \left(\sum_{i=1}^{n}x_i - n\right)\ln(1-p)
$$

**第三步，求导并令零**：

$$
\ell'(p) = \frac{n}{p} - \frac{\sum x_i - n}{1-p} = 0
$$

（第二项用了链式法则，$\frac{d}{dp}\ln(1-p) = -\frac{1}{1-p}$。）

$$
n(1-p) = p\left(\sum x_i - n\right)
$$
$$
n - np = p\sum x_i - np
$$
$$
n = p\sum x_i
$$
$$
\boxed{\hat p = \frac{n}{\sum_{i=1}^{n}X_i} = \frac{1}{\bar X}}
$$

**第四步，验证（我补充）**：

$$
\ell''(p) = -\frac{n}{p^2} - \frac{\sum x_i - n}{(1-p)^2} < 0 \quad (\text{因 } \sum x_i \ge n \text{ 恒成立})
$$

**为什么 $\sum x_i \ge n$ 恒成立？** 因为每个 $x_i \ge 1$（最小值是 1，因为"第一次试验就成功"也至少要用 1 次），所以 $\sum x_i \ge n$，从而 $\sum x_i - n \ge 0$，第二项为非正。于是 $\ell''(p) < 0$ 恒成立，$\ell$ 严格凹，$\hat p$ 是全局最大。

**结果解读**：**$\hat p = 1/\bar X$，即"平均试验次数的倒数"。** 这个结果和前面三个例子的"$\hat\theta = \bar X$"形式不同，原因就是 $E[X] = 1/p$ 而不是 $p$。**反过来说，这正好也体现了"理论均值 = 样本均值"这个原则：令 $E[X] = 1/p = \bar X$，解出 $p = 1/\bar X$。** 所以四个例子其实是同一个原则。

**一个必须提防的边界（我补充）**：几何分布的参数空间是**开区间** $p \in (0,1)$，**不含 0 和 1**。这意味着 $\hat p = 1/\bar X$ 在有限样本下永远取不到 0 或 1，所以最优点严格在内部，**开区间不构成问题**——这和 Bernoulli 的闭区间情形正好形成对照，**说明参数空间写"开"还是"闭"是要看具体问题的，不是随便写的。**

（顺带验证一下数值量级：如果一次试验成功的概率 $p = 0.1$，则平均要试验 $1/0.1 = 10$ 次。$\hat p = 1/\bar x$ 在 $\bar x = 10$ 时给出 $0.1$，合理。）

### 7.6 例 4：Uniform $[0,\theta]$——不能用求导的例子（讲义第 16 页）

**这是本讲最重要的一个例子**，因为它**打破了三步法的普适性**。题目：$X_1,\ldots,X_n$ i.i.d. 服从 $[0,\theta]$ 上的均匀分布：
$$
f(x;\theta) = \begin{cases} \dfrac{1}{\theta}, & 0 \le x \le \theta, \\[6pt] 0, & \text{otherwise},\end{cases} \qquad \theta \in (0,\infty)
$$

**先认清这个模型**：均匀分布在 $[0,\theta]$ 上"每个点等可能"，密度恒为常数 $1/\theta$（因为区间长度是 $\theta$，所以密度必须是 $1/\theta$ 才能让总面积等于 1）。**关键特征：$\theta$ 决定了密度的高度，同时又决定了支撑集的右端点。** 这个"$\theta$ 同时出现在值和定义域里"的双重身份，就是下面一切麻烦的根源。

**第一步，写似然——这次要格外小心**：
$$
L(\theta) = \prod_{i=1}^{n}f(x_i;\theta)
$$

**每个因子 $f(x_i;\theta)$ 有两种可能**：如果 $x_i \le \theta$ 则等于 $1/\theta$；如果 $x_i > \theta$ 则等于 0。而**只要有一个因子为 0，整个乘积就是 0**。什么时候所有因子都不为零？当且仅当**每一个** $x_i$ 都满足 $x_i \le \theta$，也就是
$$
\theta \ge \max\{x_1, x_2, \ldots, x_n\}
$$

于是似然函数必须**分段**写：

$$
L(\theta) = \begin{cases} \theta^{-n}, & \theta \ge \max_i x_i, \\[4pt] 0, & \theta < \max_i x_i. \end{cases}
$$

（$\theta^{-n}$ 就是 $n$ 个 $1/\theta$ 连乘的结果。）

**第二步，为什么不能用求导**（这是本页的核心 insight）：

讲义给的解法是**直接看**：

> "Solution: $\hat\theta = X_{(n)} = \max\{X_1, \ldots, X_n\}$."

这里 $X_{(n)}$ 是**第 $n$ 阶顺序统计量（order statistic）**，即样本排好序后最大的那个。**为什么是它？** 分两步论证：

**论证 1：$L(\theta) = 0$ 一律排除。** 如果 $\theta < \max_i x_i$，那就存在某个观测值超出了 $\theta$ 允许的最大范围——**观测到了"理论上不可能"的数据**，这组数据在该 $\theta$ 下的可能性是 0。所以这种 $\theta$ 直接被淘汰。

**论证 2：在剩下的区间 $\theta \ge \max_i x_i$ 上，$L(\theta) = \theta^{-n}$，这是关于 $\theta$ 的严格递减函数。** 因为 $n > 0$，$\theta$ 越小，$\theta^{-n}$ 越大（例如 $n=2$：$1/4 < 1/9 < \cdots$，$\theta = 0.5$ 时 $\theta^{-2}=4$，$\theta=0.6$ 时 $\theta^{-2}\approx 2.78$，确实随 $\theta$ 增大而减小）。

**把两条合起来**：$L(\theta)$ 在 $\theta < \max_i x_i$ 上恒为 0，然后在 $\theta = \max_i x_i$ 处**跳到最大值** $\left(\max_i x_i\right)^{-n}$，之后**单调递减**。所以最大值在**跳跃点**取得：

$$
\boxed{\hat\theta = X_{(n)} = \max\{X_1, \ldots, X_n\}}
$$

**为什么不能求导？** 三个层面，每个都值得单独记住：

1. **$\theta$ 的最优解落在参数空间 $\Omega = (0,\infty)$ 的"有效下边界"上**（更准确地说，落在由数据决定的可行区域边界 $\theta = \max_i x_i$ 上），**而不是内部驻点**。求导法找的是"内部驻点"，对边界最优解失效。这就是 8.1 节正则条件 (R3) 所要求的"$\theta_0$ 是 $\Omega$ 的内点"失效的后果。
2. **$\theta$ 出现在支撑集里**，导致 $f(x;\theta)$ 在 $x = \theta$ 处**不连续**（从 $1/\theta$ 跳到 0），因而 $L(\theta)$ 本身在 $\theta = \max_i x_i$ 处**不连续**、**不可导**。对不可导的函数求和为零的导数是没有意义的。
3. 更严格地说，这个问题违反了 8.1 节的 **(R2) 共同支撑集**条件，**这就是为什么讲义要把 (R1)–(R3) 列出来**——它们不只是理论上的装饰，Uniform 例子就是它们失效的活体标本。

**一个重要的附注（讲义未提，但很值得知道）**：这个 $\hat\theta = X_{(n)}$ 是**有偏的（biased）**。可以证明 $E[X_{(n)}] = \frac{n}{n+1}\theta$（这是均匀分布最大顺序统计量的已知结果），所以

$$
E[\hat\theta] = \frac{n}{n+1}\theta < \theta
$$

**它系统性地低估了 $\theta$**，而且**样本量越小，偏得越厉害**（$n=1$ 时 $E[\hat\theta] = \theta/2$！）。当 $n\to\infty$ 时 $\frac{n}{n+1}\to 1$，偏差消失，所以它是**渐近无偏的（asymptotically unbiased）**。这个例子说明：**MLE 不保证无偏**——这正是**下一讲（无偏性与有效性）的引子**。这是 MLE 最著名的"缺点"之一（另一个是它可能给出无意义的边界解）。

#### 7.6.1 黑板补充：用指示函数（indicator function）重写这一整套推导

上面我们用"分段函数"（cases）写 $L(\theta)$。课堂板书给了一个**更紧凑、也更严谨**的写法——引入**指示函数（indicator function）**，用一个公式同时表达"值是多少"和"什么时候为 0"。板书写的是：

$$
f(x;\theta) = \frac{1}{\theta}\,\mathbb{1}\left\{x \in [0,\theta]\right\}, \qquad
L(\theta) = \prod_{i=1}^{n}\frac{1}{\theta}\,\mathbb{1}\left\{x_i \in [0,\theta]\right\}
= \frac{1}{\theta^{n}}\,\mathbb{1}\left\{0 \le \min_i\{x_i\},\ \max_i\{x_i\} \le \theta\right\}
$$

$$
\theta_{\text{MLE}} = \max\{x_1, \ldots, x_n\}
$$

**（1）指示函数是什么**：$\mathbb{1}\{A\}$（读作"indicator of $A$"）是一个**只取 0 或 1 的函数**，定义为

$$
\mathbb{1}\{A\} = \begin{cases} 1, & \text{若条件 } A \text{ 成立} \\ 0, & \text{若条件 } A \text{ 不成立}\end{cases}
$$

比如 $\mathbb{1}\{x \in [0,\theta]\}$ 就是"$x$ 落在 $[0,\theta]$ 里时为 1、否则为 0"。**它的作用就是"把分段函数压进一个公式"**——原本要写"当 $0\le x\le\theta$ 时取 $1/\theta$，否则取 0"，现在写成 $\frac{1}{\theta}\mathbb{1}\{x\in[0,\theta]\}$，一行搞定。

**注意板书这一步并不是"新推导"，而是把上面那个 $\begin{cases}\cdot\\\cdot\end{cases}$ 用指示函数重写了一遍**。两者完全等价，但指示函数的好处是**可以塞进连乘号里、可以代数运算**，而分段函数不行。

> **关于区间端点的开闭（课堂抄录作 $[0,\theta)$）**：抄录笔记里这一行写的是 $f(x;\theta) = \frac{1}{\theta}\,\mathbb{1}\{x\in[0,\theta)\}$，**右端是开的**；本笔记上文写的是闭区间 $[0,\theta]$。两种写法在本题**完全等价、不影响任何结论**，原因有两条：
> 1. **端点只是一个点，概率为 0**。$\int_0^\theta \frac1\theta dx = \int_0^{\theta^-}\frac1\theta dx = 1$，端点取不取不影响归一化，也不影响 $\Pr(a<X\le b)$ 的取值（第 1 讲 3.4 节专门讲过这件事）。
> 2. **它只影响"$\theta$ 能否恰好等于某个 $x_i$"这种概率为 0 的边界情形**，而 $\hat\theta = \max\{x_i\}$ 这个结论在两种写法下都一样（闭区间时 $\max_i x_i \le \theta$ 含等号，开区间时严格小于，但把 $\theta$ 取到 $\max_i x_i$ 在两种情形下都是最优——闭区间能在端点取到，开区间只能趋近，而上确界相同）。
>
> **规范的写法**其实是：$\mathbb{1}\{0 \le x < \theta\}$ 或 $\mathbb{1}\{0\le x\le\theta\}$ **都可以**，教科书中两种都常见（Hogg 教材用闭区间）。关键是**别把 $\min_i x_i \ge 0$ 那一侧也写错**——那一侧若允许 $x<0$ 就真的出问题了（见下文第（3）点）。

**（2）最关键的一步：$n$ 个指示函数相乘，会塌缩成 1 个**。板书把 $\prod_{i=1}^{n}\mathbb{1}\{x_i\in[0,\theta]\}$ 直接写成了一个指示函数，这是整块板最有含金量的一步，理由是：

$$
\prod_{i=1}^{n}\mathbb{1}\{A_i\} = \mathbb{1}\left\{\bigcap_{i=1}^{n} A_i\right\}
$$

**乘积只有在所有因子都为 1 时才是 1，否则一旦有一个因子为 0，整个乘积就是 0。** 所以"$n$ 个指示函数相乘"等价于"**所有条件同时成立**"这一个条件。这是指示函数的通用运算规则（乘法 = 取交集），值得单独记住。

把它套到本题：条件 "$x_i \in [0,\theta]$ **对每一个** $i$ 都成立"等价于

$$
\min_i\{x_i\} \ge 0 \quad\text{且}\quad \max_i\{x_i\} \le \theta
$$

**为什么 "对所有 $i$" 能换成 "$\min$ 和 $\max$"？** 因为"每个 $x_i$ 都 $\le \theta$"这件事，只要**最大的那个**不超过 $\theta$ 就自动全部满足；"每个 $x_i$ 都 $\ge 0$"只需**最小的那个**不小于 0 就全部满足。**用两个极端值就能代表 $n$ 个不等式——这一步把 $n$ 个约束压缩成 2 个约束**，也正是 Uniform 例子里会出现 $\max\{x_i\}$ 的根本原因。

**（3）这两个约束的地位完全不同，这是指示函数写法最清楚的地方**：

- **$\min_i\{x_i\} \ge 0$ 这一条不含 $\theta$**。它是**对数据本身的一个检查**：如果某个观测值是负数，那么**无论 $\theta$ 取什么值**，$L(\theta)$ 都恒为 0——因为模型 $[0,\theta]$ 根本无法产生负的数据。这种情况下**不存在 MLE**（似然处处为 0，无从最大化）。实践中我们默认数据合法，这一条就自动满足了。
- **$\max_i\{x_i\} \le \theta$ 这一条才是真正约束 $\theta$ 的**。它要求 $\theta$ 不小于样本最大值。

**把两层合起来**，指示函数在且仅在

$$
\theta \ge \max_i\{x_i\}
$$

时取 1，于是

$$
L(\theta) = \begin{cases} \theta^{-n}, & \theta \ge \max_i x_i \\ 0, & \text{否则}\end{cases}
$$

**这正是前面用分段函数写出的那个 $L(\theta)$——两条路殊途同归，说明前面那套"直接看"的推导没有问题。** 指示函数写法的价值在于：它**一眼就能看出 $L$ 在哪里是不连续的**（$\mathbb{1}$ 本身就是个台阶函数，在 $\theta = \max_i x_i$ 处从 0 跳到 1），因此**"不能用求导"这个结论不再需要额外论证，而是记号本身自带的**。

**（4）最大化过程**：既然指示函数把可行域限制在 $\theta \in [\max_i x_i,\ \infty)$，而在这个区间上 $L(\theta) = \theta^{-n}$ 是**关于 $\theta$ 严格递减**的，那么最优解就是**可行域里最小的那个 $\theta$**：

$$
\hat\theta = \max\{x_1,\ldots,x_n\}
$$

**这个"取最小可行值"的逻辑可以类比成"顺着地板往下推"**：$L(\theta)$ 像一面从左上往右下倾斜的坡（$\theta$ 越小越高），但左侧被一堵墙（指示函数在 $\theta = \max x_i$ 处的台阶）挡住了，**所以能站到的最高点就在墙边**。

**（5）这个记号在考试里有什么用**：以后遇到"支撑集依赖参数"的密度（Uniform、Pareto、平移指数分布等），标准做法就是：

$$
f(x;\theta) = \text{(光滑部分)} \times \mathbb{1}\{\text{由 } \theta \text{ 决定的可行条件}\}
$$

**把"光滑部分"和"可行条件"分开写**，光滑部分正常取对数求导（这里就是 $\ell(\theta) = -n\ln\theta$，导数 $-n/\theta < 0$ 恒负，说明单调递减），可行条件则负责把 $\theta$ 限制在 $\theta \ge \max_i x_i$ 上。**两部分各管各的，最后取"光滑部分的极值方向"与"可行域边界"的交集**，就是 MLE。这套流程比死记"Uniform 的答案是 $\max$"要可靠得多。

### 7.7 黑板例题：Poisson($\lambda$) 的 MLE——并闭合了整讲的逻辑循环

这是课堂板书上**新增的、讲义里没有的第五个例子**，也是本讲最有价值的一块内容。原因不在例题本身难度，而在于它**把第 4 节那个"随手凑出来"的估计量证明成了 MLE**——整讲的实践部分和理论部分在这里合上了。

**题目**：$X_1, \ldots, X_n \overset{iid}{\sim} \text{Poisson}(\lambda)$，PMF 为

$$
f(x;\lambda) = \frac{\lambda^{x}}{x!}e^{-\lambda}, \quad x = 0, 1, 2, \ldots, \quad \lambda \in (0,\infty)
$$

参数空间 $\Omega = (0, \infty)$。**先认清模型**：Poisson 分布描述"单位时间（或单位面积）内稀有事件发生的次数"（第 1 讲笔记第 4.2 节），$E[X] = \mathrm{Var}(X) = \lambda$。**注意 $\lambda$ 既不是"概率"也不是"比例"，而是"平均发生次数"**，所以它可以是任意正数。$x!$ 是阶乘（$0! = 1$）。

**① formulate $L(\lambda)$：**

$$
L(\lambda) = \prod_{i=1}^{n} P(X_i = x_i;\lambda) = \prod_{i=1}^{n}\frac{\lambda^{x_i}}{x_i!}e^{-\lambda} = \frac{\lambda^{\sum_{i=1}^{n}x_i}}{\prod_{i=1}^{n}\left(x_i!\right)}\, e^{-n\lambda}
$$

**这一行的压缩过程要逐步看清**，三个部分分别处理：

$$
\prod_{i=1}^{n}\lambda^{x_i} = \lambda^{\sum_{i=1}^{n}x_i}
\quad\text{（指数相加）}
$$

$$
\prod_{i=1}^{n}e^{-\lambda} = e^{-\lambda}\cdot e^{-\lambda}\cdots e^{-\lambda} = e^{-n\lambda}
\quad\text{（$n$ 个 $e^{-\lambda}$ 相乘，指数相加变成 $-n\lambda$）}
$$

$$
\prod_{i=1}^{n}\frac{1}{x_i!} = \frac{1}{\prod_{i=1}^{n}\left(x_i!\right)}
\quad\text{（分母连乘，留在分母上）}
$$

把三块拼起来就得到板书那一行。**这一步是整道题的关键——尤其 $e^{-n\lambda}$ 那个 $-n\lambda$，最容易漏掉 $n$。**

> **✅ 与课堂抄录笔记核对（2026-09-15）**：抄录里的这一行与上面**完全一致**，只是有几处输入时的小遗漏，逐条列出以免抄错：
> | 抄录原文 | 应为 | 说明 |
> | --- | --- | --- |
> | $L(\lambda) = \prod P(x_i = x_i\,i\lambda)$ | $\prod_{i=1}^n P(X_i = x_i;\lambda)$ | 分号 $;$ 被输入成了 `i`；**参数与观测值之间用分号**，不是竖线 $\mid$（$\mid$ 是条件概率的记号，含义不同） |
> | $\lambda^{\sum^{n}_{i=1}}$ | $\lambda^{\sum_{i=1}^{n}x_i}$ | 求和号的上限下角标写全了，但**漏了被求和的 $x_i$** |
> | $e^-n\lambda$ | $e^{-n\lambda}$ | 负号的范围要括住 $n\lambda$ |
> | $\ell(\lambda) = (\sum x_i)\ln\lambda - n\lambda - \ln(\prod(x_i!))$ | 同上 | ✅ **完全正确**，与讲义推导一致 |

**② 取对数得 $\ell(\lambda)$：**

$$
\ell(\lambda) = \left(\sum_{i=1}^{n}x_i\right)\log\lambda \;-\; n\lambda \;-\; \log\left(\prod_{i=1}^{n}\left(x_i!\right)\right)
$$

**这一行由三条对数法则拼成**：

$$
\log\left(\frac{A}{B}\right) = \log A - \log B \quad\text{（分式拆成减法）}
$$
$$
\log\left(\lambda^{\sum x_i}\right) = \left(\sum x_i\right)\log\lambda \quad\text{（幂变系数）}
$$
$$
\log\left(e^{-n\lambda}\right) = -n\lambda \quad\text{（$\log$ 与 $e$ 互逆）}
$$

**关键观察（板书特意用括号标出了 "(ln)" 和 "(e)" 就是在提示这一点）**：

- **第三个 $-\log\left(\prod x_i!\right)$ 项与 $\lambda$ 完全无关**，它是一个**常数**。求导时直接消失，对最优点毫无影响。**所以从第②步开始就可以把它扔掉**，这也是板书的实际操作——一阶导里它确实不在。
- **这揭示了一个通用原则：$\ell(\theta)$ 里所有不含 $\theta$ 的项都可以在求最大化时丢掉**，因为它们对 $-\ell$ 的"形状"没有贡献，不改变峰的位置。这个技巧在计算量大的模型（比如回归、混合模型）里是常规操作，能省掉大量无用工作。**但要小心：只有当这些项真的不含 $\theta$ 时才能丢**（例如 Poisson 的 $n\lambda$ 项含 $\lambda$，绝不能丢）。

**③ 解得分方程：**

$$
\frac{\partial \ell(\lambda)}{\partial \lambda} = \frac{\sum_{i=1}^{n}x_i}{\lambda} - n = \frac{n\bar x}{\lambda} - n = 0
$$

（用了 $\frac{d}{d\lambda}\log\lambda = \frac{1}{\lambda}$ 和 $\frac{d}{d\lambda}(-n\lambda) = -n$。中间那步 $\sum x_i = n\bar x$ 是板书的写法，和 7.3 节把 $\sum x_i$ 换成 $n\bar x$ 是同一个习惯。）

解方程：

$$
\frac{n\bar x}{\lambda} = n \ \Longrightarrow\ \bar x = \lambda \ \Longrightarrow\ \boxed{\hat\lambda = \bar x}
$$

**这个方程的形状值得记住**：它在说"**单位时间的理论平均发生次数 $\lambda$ = 观测到的平均每次发生次数 $\bar x$**"。也就是前面反复出现的"**理论均值 = 样本均值**"原则。

**④ 验证二阶条件（板书完整地做了这一步，用的是 $\ell''<0$ 的负号形式）：**

$$
\frac{\partial^2 \ell(\lambda)}{\partial \lambda^2} = -\frac{\sum_{i=1}^{n}x_i}{\lambda^2} = -\frac{n\bar x}{\lambda^2}
$$

代入 $\lambda = \hat\lambda = \bar x$：

$$
\left.-\frac{\partial^2 \ell(\lambda)}{\partial \lambda^2}\right|_{\lambda=\hat\lambda}
= -\left(-\frac{n\bar x}{\lambda^2}\right)_{\lambda=\hat\lambda}
= \frac{n\bar x}{\bar x^{2}}
= \frac{n}{\bar x} > 0 \quad \checkmark
$$

**为什么 $>0$？** 因为 $n > 0$ 且 $\bar x > 0$（Poisson 观测值非负、且不可能全为 0 时均值才为正；若全为 0 则 $\bar x = 0$ 需要单独讨论边界，此时 $\lambda\to 0$）。既然"负的二阶导大于零"，等价于二阶导小于零，$\ell$ 在该点是**凹的**，$\hat\lambda$ 是最大值点。**注意板书这一行同时演示了三件事：算二阶导、代回 $\hat\lambda$、验符号，这正是 7.2 节第③步的标准操作流程。**

**最终结果**：

$$
\hat\lambda = \bar x = \frac{1}{n}\sum_{i=1}^{n}x_i
$$

#### 7.7.1 为什么这个例题很重要：它把第 4 节的"随手估计"变成了 MLE

回到本讲第 4 节。那里我们为了预测迈阿密大学明年的 Covid 情况，**凭直觉写了两个估计量**，并且明确说过它们是"临时凑出来的、不知道好在哪"（见 4.3 节）。现在板书给出了答案——**那两个估计量都是 MLE，我们的直觉是对的。**

**（1）Poisson 的 $\lambda$ ↔ 4.1 节的 `mu = sum(covid_fs$Positive)`**

4.1 节把教职工**每一天**的阳性数当成一组观测 $x_1, x_2, \ldots, x_{n}$（$n = 358$ 天），并且**用"全年阳性总数"直接当成了 Poisson 的参数**：

$$
\text{\texttt{mu}} = \sum_{i=1}^{n}x_i = 788
$$

现在用本节结果核对一下，**这里其实有两层，必须分清**：

- **日感染率**的 MLE 是 $\hat\lambda = \bar x$。我在 3.3 节复算过：教职工组的 `Positive` 均值恰为 **2.201**，也就是
  $$
  \hat\lambda = \bar x = \frac{788}{358} = 2.2011\ldots
  $$
  **这正好等于 `summary(covid_fs[,4:7])` 输出的那个 `Mean`！** 而 3.3 节里 `summary()` 的 `Mean` 和 `Median`、`Min`、`Max` 一起被当作"描述统计量"抄下来，我们当时并没有意识到**其中那个均值同时也是一个参数估计量**。现在知道了：**`Mean` 这一格就是 Poisson 率参数的 MLE。**
- **全年总数**的速率是 $n\lambda$。因为**独立 Poisson 变量之和仍是 Poisson 变量、且参数相加**（第 1 讲的 MGF 方法可以直接证明，或理解为"把 358 个独立的时间窗拼成一整年"），所以全年阳性总数 $S = \sum_{i=1}^{n}X_i$ 服从 $\text{Poisson}(n\lambda)$。把 $\hat\lambda$ 代进去：
  $$
  \widehat{n\lambda} = n\hat\lambda = n\bar x = \sum_{i=1}^{n}x_i = 788
  $$
  **所以 4.1 节那行 `mu = sum(covid_fs$Positive)` 给出的 788，正是"全年速率 $n\lambda$ 的 MLE"，一字不差。**

**（2）Bernoulli/Binomial 的 $p$ ↔ 4.2 节的 `p = sum(covid_fs$Positive)/16000`**

4.2 节要算"统计系 20 位教职工里有几位被感染"，为此需要**一个人一年内被感染的几率**，讲义写的是：

$$
p = \frac{788}{16000} = 0.04925
$$

把它重新表述一遍：把**全校 16000 位教职工**每一位看作**一次 Bernoulli 试验**——某位教职工"被测出阳性"记为 $1$、否则记为 $0$。那么这 16000 个观测里有 $788$ 个 $1$，样本均值就是

$$
\bar x = \frac{\text{阳性人数}}{\text{总人数}} = \frac{788}{16000}
$$

**这正是 4.2 节用的那个 $p$。** 而 7.3 节刚证明了 **Bernoulli 的 MLE 就是 $\hat p = \bar x$**。所以 4.2 节那个 $p$ **也是 MLE**，不是随手写的。

**（3）把两张图的对应关系整理成表：**

| 第 4 节的"随手估计" | 对应的模型 | 板书证明它是什么 | 一致性 |
| --- | --- | --- | --- |
| $\hat\lambda = \bar x = 2.201$（日感染率） | $\text{Poisson}(\lambda)$ 的每日计数 | 7.7 节：$\hat\lambda = \bar x$ | ✓ |
| $\text{\texttt{mu}} = 788$（全年总数） | $\text{Poisson}(n\lambda)$，$n = 358$ 天 | 7.7 节 + 独立 Poisson 可加性：$n\hat\lambda = 788$ | ✓ |
| $p = 788/16000 = 0.04925$ | $\text{Bernoulli}(p)$ 逐个体建模 | 7.3 节：$\hat p = \bar x$ | ✓ |

**这张表就是本讲的主线闭环**：第 1–4 节从"数据长什么样"出发，一路做到"预测明年"，过程中用了几个直觉性的估计；第 5–8 节建立通用理论（似然、MLE、正则条件、支撑定理），最后用一个 Poisson 例题**回过头证明了前面的直觉做法确实是最优的**。

**这也是"为什么统计学家总在推公式"的答案**：直觉在简单问题里往往能猜对（这次三处全对），但**一旦问题变复杂（多参数、支撑集含参数、数据不独立），直觉就没有指南针了**。MLE 的价值在于它给出一个**任何问题都能照着做的流程**，并且在正则条件下有"渐近必然正确"的保证。**换句话说，直觉负责让你在简单情形下猜对，理论负责告诉你什么时候直觉会错。**

> **顺带一个对照（我补充，讲义与板书都未提）**：如果把"理论均值 = 样本均值"这条原则硬套到 7.6 节的 Uniform $[0,\theta]$ 上，因为 $E[X] = \theta/2$，会解出 $\tilde\theta = 2\bar x$——这叫**矩估计量（Method of Moments estimator）**。但 Uniform 的 MLE 是 $\hat\theta = X_{(n)} = \max\{X_i\}$。**两者不同**（$2\bar x$ 通常大于 $X_{(n)}$）。这说明**"理论均值 = 样本均值"只是 MLE 在指数族下的巧合，不是普遍规律**；MLE 的定义永远是"最大化 $L$"，而不是"配均值"。下节课学矩估计法时会正式看到这两种方法的系统差异。

### 7.8 五个例子的对照表

| 分布 | 参数空间 $\Omega$ | 似然 $L(\theta)$ | 得分方程 | MLE $\hat\theta$ | 求导法可用？ |
| --- | --- | --- | --- | --- | --- |
| Bernoulli($p$) | $\{p: 0 \le p \le 1\}$（闭） | $p^{\sum x_i}(1-p)^{n-\sum x_i}$ | $\dfrac{\sum x_i}{p} - \dfrac{n-\sum x_i}{1-p} = 0$ | $\hat p = \bar X$ | 可以（$\ell''<0$） |
| **Poisson($\lambda$)（板书）** | $(0,\infty)$ | $\dfrac{\lambda^{\sum x_i}}{\prod (x_i!)}e^{-n\lambda}$ | $\dfrac{\sum x_i}{\lambda} - n = 0$ | $\hat\lambda = \bar X$ | 可以（$-\ell''=\frac{n}{\bar x}>0$） |
| Exponential($\theta$) | $(0,\infty)$ | $\theta^{-n}e^{-\sum x_i/\theta}$ | $-\dfrac{n}{\theta} + \dfrac{\sum x_i}{\theta^2} = 0$ | $\hat\theta = \bar X$ | 可以（$\ell''=-\frac{n}{\bar x^2}<0$） |
| Geometric($p$) | $(0,1)$（开） | $p^n(1-p)^{\sum x_i - n}$ | $\dfrac{n}{p} - \dfrac{\sum x_i - n}{1-p} = 0$ | $\hat p = \dfrac{1}{\bar X} = \dfrac{n}{\sum X_i}$ | 可以（$\ell''<0$） |
| Uniform $[0,\theta]$ | $(0,\infty)$ | $\dfrac{1}{\theta^{n}}\mathbb{1}\!\left\{\max_i x_i \le \theta\right\}$（等价于分段式） | （不存在，$\ell'=-n/\theta<0$ 恒负） | $\hat\theta = X_{(n)} = \max\{X_i\}$ | **不可以**（指示函数造成不可导） |

**从这张表里能提炼出两条规律**：

**规律一（前四个）**：它们的 MLE 都来自**"让理论均值等于样本均值"**——

$$
E[X] = \bar x \quad\Longrightarrow\quad
\begin{cases}
p = \bar x & \text{(Bernoulli，因为 } E[X]=p) \\
\lambda = \bar x & \text{(Poisson，因为 } E[X]=\lambda) \\
\theta = \bar x & \text{(Exponential，因为 } E[X]=\theta) \\
1/p = \bar x \Rightarrow p = 1/\bar x & \text{(Geometric，因为 } E[X]=1/p)
\end{cases}
$$

这四个都属于**指数族（exponential family）且支撑集不依赖于参数**，所以求导法畅通无阻。

**规律二（Uniform）**：因为**支撑集 $[0,\theta]$ 依赖参数 $\theta$**，$\ell$ 在 $\theta = \max x_i$ 处不连续、不可导，最优解落在可行区域边界上，必须直接比较而非求导。

**方法论启示**：**看到题目先问"支撑集是否含参数"**——不含 → 放心用①②③求导；含 → 立刻警觉，回去看 $L(\theta)$ 的分段结构，找最大值跳变点。这一个判断就能决定整道题的解法。

---

## 8. 为什么要最大化似然函数？（讲义第 17–18 页）

讲义在这里插入了本讲最"理论"的一页半。表面上是证明，实际上是**回答一个诚实的问题：凭什么认定"最大化似然"这个做法是对的？** 前面四道题我们都把 $L(\theta)$ 最大化，但这只是"看起来合理"，还需要理论支撑。

### 8.1 正则条件（Regularity Conditions）

讲义第 17 页用 Assumption 框给出三条：

> **(R1) The PDFs are distinct: $\theta \ne \theta' \Rightarrow f(x_i;\theta) \ne f(x_i;\theta')$.**

**（R1）可识别性（identifiability）**：不同的参数值必须对应**不同的**分布。为什么需要它？**如果两个不同的 $\theta$ 产生完全一样的分布，那么无论有多少数据、无论用什么方法，都不可能区分这两个 $\theta$**——数据里根本没有关于"是哪一个"的信息。这时候谈"估计 $\theta$"就是在做一件不可能的事。

举个反例体会一下：如果把正态分布参数化为 $f(x;\theta) = \frac{1}{\theta}e^{-x^2/(2\theta)}$（这里 $\theta$ 是方差），那没问题。但如果写成 $f(x;\theta) = \frac{1}{|\theta|}e^{-x^2/(2\theta^2)}$（$\theta$ 是标准差），那么 $\theta$ 和 $-\theta$ 给出同一个分布——**这时候必须把参数空间限制成 $\theta > 0$ 才能满足 (R1)**。所以 (R1) 常常是靠**限制参数空间**来保证的。

> **(R2) The PDFs have common support for all $\theta$.**

**（R2）共同支撑集**：所有 $\theta \in \Omega$ 对应的密度，$f(x;\theta) > 0$ 的 $x$ 范围必须**完全相同**（不随 $\theta$ 变）。

这一条正是 **7.6 节 Uniform 例子违反的条件**：$\theta$ 一变，支撑集 $[0,\theta]$ 就变了。违反 (R2) 会导致 $\ell$ 不连续、不可导，$\max$ 跑到边界上去。

> **(R3) $\theta_0$ is an interior point of $\Omega$.**

**（R3）真值是参数空间的内点**：$\theta_0$（真实的参数值）必须落在 $\Omega$ 的**内部**，不能是端点。这一条保证了**求导法在真值附近是有效的**——因为真值不在边界上，那么以很大概率最优解也不在边界上，于是"令导数为零"这个动作是合法的。

**三条条件的分工总结**：(R1) 保证"问题有唯一答案"，(R2) 保证"似然函数足够光滑"，(R3) 保证"最优解落在内部、可以用微积分去找"。**三条一起，才能支撑下一个定理。**

### 8.2 定理：渐近地，真值处似然最大

> **Theorem.** Let $\theta_0$ be the true parameter, under assumptions (R1)–(R3), we have
> $$\lim_{n\to\infty} P_{\theta_0}\left[L(\theta_0;\mathbf{x}) > L(\theta;\mathbf{x})\right] = 1, \quad \forall \theta \ne \theta_0.$$

**逐项解释这个式子（每个符号都要读懂）**：

- **$\theta_0$**：the true parameter，**真实的参数值**。在频率派框架下它是个固定的、未知的常数。
- **$P_{\theta_0}[\cdot]$**：下标 $\theta_0$ 表示"**在真值为 $\theta_0$ 的世界里计算的概率**"。也就是说，数据 $\mathbf{x}$ 是按 $f(\cdot;\theta_0)$ 生成的，我们在这样的世界里问"某个事件发生的概率是多少"。
- **$L(\theta_0;\mathbf{x}) > L(\theta;\mathbf{x})$**：真值处的似然值**大于**任意其他候选值 $\theta$ 处的似然值。
- **$\forall\theta \ne \theta_0$**：这个结论对**每一个**不同于真值的 $\theta$ 都成立。
- **$\lim_{n\to\infty}(\cdots) = 1$**：当样本量趋于无穷时，上述事件的概率趋于 1。

**定理的完整含义**：**只要样本量足够大，真值 $\theta_0$ 处的似然值几乎必然会超过任何错误候选值 $\theta$ 的似然值。**

**这个定理解决了什么？** 它把我们"最大化似然"的动作从"看起来合理"升级为"**渐近意义下必然正确**"：

- 既然 $L$ 的最大值（在大样本下）几乎总是在真值处取得，
- 那么**取使 $L$ 最大的那个 $\theta$ 作为估计，就是取真值**。
- 所以 MLE $\hat\theta = \arg\max L(\theta)$ 是**相合的（consistent）**——$n$ 越大，它越接近真值。

**用大白话说**：这个定理在说"**似然的峰，大样本时长在真值头上**"。讲义第 18 页第一句正是这个意思：**"The theorem implies that asymptotically the likelihood function $L$ is maximized at the true value $\theta_0$."**

**必须牢记的两个 caveat**：

1. **这是"渐近（asymptotic）"结论，不是"有限样本"结论。** 定理里有 $n \to \infty$。对固定的 $n = 20$，似然的峰**完全可能不在真值处**（甚至可能偏得很远）。而且定理只保证"真值的似然大于任何**固定的**错误值"，对"错误值随 $n$ 一起变化"的情形不直接适用。**有限样本的性质（无偏性、方差大小）是下一讲的内容，本讲没有触及。**
2. **它是概率性的（$P\to 1$），不是必然的。** "趋于 1"意味着**存在**小概率的失败情形，只是这个概率随 $n$ 增大而消失。所以 MLE 在**某一次具体抽样**中给出一堆错答案，是可能的。
3. **讲义自己也说了这不考**：原文 **"Note: This theorem is not required in this course. It is helpful to understand the concept of MLE better."** 所以**不需要背证明**，但**要能说清这个定理在回答什么问题**（"为什么最大化似然是对的"），以及三条正则条件各自的作用。

### 8.3 MLE 的正式定义（讲义第 18 页）

讲义第 18 页最后用 Definition 框把 MLE 的定义再正式地写了一遍：

> "We say that $\hat\theta = \hat\theta(X_1,\ldots,X_n)$ is a maximum likelihood estimator (MLE) of $\theta$ if
> $$\hat\theta = \arg\max L(\theta; X_1, \ldots, X_n),$$
> where the notation $\arg\max$ means that $L(\theta; X_1,\ldots,X_n)$ achieves its maximum value at $\hat\theta$."

**注意这里和 7.1 节定义的两处差别**，都不是废笔：

- **$\hat\theta = \hat\theta(X_1,\ldots,X_n)$ 显式写出了它的变量**。这提醒我们：**MLE 是一个估计量（estimator），是随机变量的函数，本身也是随机变量**——回到 5.3 节那个大小写约定。写 $\hat\theta(X_1,\ldots,X_n)$ 用的是大写 $X$，正是因为它是抽样之前就确定好的"规则"；等到代入具体数据才得到 $\hat\theta(x_1,\ldots,x_n)$ 这个估计值。
- **$L(\theta; X_1,\ldots,X_n)$ 里 $X$ 也写成了大写**，强调似然函数是"随样本随机变化的一族函数"——**每次抽样都会画出不一样的似然曲线，峰的位置也会抖动。** 这就是为什么"MLE 准不准"是一个概率论问题，而不是一个算术问题。

**逻辑链条的收尾**：讲义第 18 页把整条推理线串起来了——**定理说"渐近地 $L$ 在真值处最大" → 所以在估计 $\theta_0$ 时，自然会考虑"使 $L$ 最大的那个 $\theta$" → 于是有了 MLE 的定义。** 这是本讲从"直觉做法"到"有原理支撑的方法"的完整闭环。

---

## 9. 一页纸速查表

**数据可视化（第 1–2 节）**

| 概念 | 定义 / 公式 | 关键点 |
| --- | --- | --- |
| 直方图 | 把连续观测分箱，柱高 = 相对频数或密度 | **面积** ∝ 观测数，与 PDF 的"面积 = 概率"对接 |
| 柱高（相对频数） | $\dfrac{n_j}{n}$（$n_j$ 为该箱观测数） | 柱高之和 $=1$；**等宽时**面积之和也 $=1$ |
| 柱高（密度） | $\dfrac{n_j}{w_j n}$（$w_j$ 为组距） | 面积 $\sum_j w_j\frac{n_j}{w_j n}=1$，**恒成立**；不等宽时必须用密度 |
| 组距取舍 | 太小 → overfitting（假峰谷）；太大 → 掩盖细节 | 偏差–方差权衡；软件可自动选 bin 数 |
| 五数概括 | Min, $Q_1$, Median, $Q_3$, Max | 箱线图的全部原料 |
| IQR | $Q_3 - Q_1$ | 稳健的离散度（抵抗离群点） |
| 内 / 外栅栏 | $Q_1 - 1.5\,\mathrm{IQR}$、$Q_3 + 1.5\,\mathrm{IQR}$；$Q_1 - 3\,\mathrm{IQR}$、$Q_3 + 3\,\mathrm{IQR}$ | $1.5$ 与 $3$ 是经验常数 |
| 须 | 下须 $= \max $(下内栅栏, Min)；上须 $= \min $(上内栅栏, Max) | 须**不越过**内栅栏 |
| 两级离群点 | 可疑：内外栅栏之间；确定：超出外栅栏 | R 默认只实现单层（$1.5\,\mathrm{IQR}$） |
| 偏度判断 | 下须长 → 左偏；上须长 → 右偏 | 看**须的长度对比**，不看箱体 |

**参数估计框架（第 5–6 节）**

| 概念 | 记号 / 定义 |
| --- | --- |
| 参数空间 | $\Omega$：$\theta$ 所有允许取值的集合（正态：$\Omega=\{(\mu,\sigma^2): -\infty<\mu<\infty,\,0<\sigma^2<\infty\}$） |
| 估计量 | $u(X_1,\ldots,X_n)$，样本的函数，**随机变量**（不含量未知参数） |
| 估计值 | $u(x_1,\ldots,x_n)$，代入实际数据后的**一个数** |
| 点估计量 | 输出单个值的估计量 |
| 偏差（Bias） | $\text{Bias}(\hat\theta) = E(\hat\theta)-\theta$；$=0$ 则**无偏**（下一讲） |
| 方差 | $\operatorname{Var}(\hat\theta) = E[(\hat\theta-E\hat\theta)^2]$，衡量估计量自身的抖动（下一讲） |
| 均方误差（MSE） | $\operatorname{MSE}(\hat\theta)=E[(\hat\theta-\theta)^2]=\operatorname{Var}(\hat\theta)+[\text{Bias}(\hat\theta)]^2$（下一讲） |
| 相合性 | $\forall\varepsilon>0:\ \lim_{n\to\infty}\Pr(\lvert\hat\theta-\theta\rvert>\varepsilon)=0$，即 $\hat\theta\xrightarrow{P}\theta$（下一讲） |
| 似然函数（离散） | $L(\theta) = P(X_1=x_1,\ldots,X_n=x_n;\theta) \overset{iid}{=} \prod_{i=1}^{n}P(X_i=x_i;\theta)$ |
| 似然函数（连续） | $L(\theta) = f(x_1,\ldots,x_n;\theta) \overset{iid}{=} \prod_{i=1}^{n}f(x_i;\theta)$ |
| 对数似然 | $\ell(\theta) = \ln L(\theta) = \sum_{i=1}^{n}\ln f(x_i;\theta)$（连乘 → 求和） |
| 记号约定 | $\ln L(\theta) \triangleq \ell(\theta)$（$\triangleq$ 读作"定义为"） |

**MLE（第 7–8 节）**

| 项目 | 内容 |
| --- | --- |
| 定义 | $\hat\theta = \arg\max_{\theta\in\Omega} L(\theta) = \arg\max_{\theta\in\Omega}\ell(\theta)$（$\ln$ 单调，等价） |
| **板书解题三步** | ① formulate $L(\theta)$；② $\dfrac{\partial\ell(\theta)}{\partial\theta}=0 \Rightarrow \hat\theta$；③ $\left.-\dfrac{\partial^2\ell(\theta)}{\partial\theta^2}\right\vert_{\theta=\hat\theta}>0 \Rightarrow \hat\theta$ is MLE |
| ② 的别名 | 得分方程 / score equation；左边 $\dfrac{\partial\ell}{\partial\theta}$ 叫**得分函数 score function** |
| ③ 的别名 | 二阶条件；多参数时换成**海森矩阵负定** $-\dfrac{\partial^2\ell}{\partial\theta\,\partial\theta^{\mathsf T}} \prec 0$ |
| 通用直觉 | 单参数指数族（且支撑集不含参数）：**理论均值 = 样本均值** |
| 五大例题 | Bernoulli $\hat p=\bar x$；**Poisson $\hat\lambda=\bar x$**；Exponential $\hat\theta=\bar x$；Geometric $\hat p=1/\bar x$；Uniform $\hat\theta=X_{(n)}$ |
| 失效情形 | 支撑集依赖参数（Uniform）、最优解在边界、$L$ 不可导 |
| 正则条件 | (R1) 可识别性 (R2) 共同支撑集 (R3) 真值是内点 |
| 支撑定理 | $n\to\infty$ 时 $P_{\theta_0}[L(\theta_0)>L(\theta)]\to 1$，$\forall\theta\ne\theta_0$ ⇒ MLE 相合 |

**第 4 节估计量与 MLE 的对应（板书闭合的循环）**

| 讲义中"随手"的估计 | 其实是什么 |
| --- | --- |
| `mu = sum(covid_fs$Positive)` $= 788$ | $\text{Poisson}$ 全年速率 $n\lambda$ 的 MLE $= n\hat\lambda = n\bar x$ |
| 教职工 `Positive` 的 `Mean` $= 2.201$ | 日感染率 $\lambda$ 的 MLE $\hat\lambda = \bar x$ |
| `p = sum(covid_fs$Positive)/16000` $= 0.04925$ | $\text{Bernoulli}$ 的 MLE $\hat p = \bar x$ |

**R 函数速查（`d/p/q/r` 规律）**

| 前缀 | 含义 | 例 |
| --- | --- | --- |
| `d` | 密度 / 质量函数 PMF·PDF | `dbinom(0,20,p)`、`ppois` 的对应是 `dpois` |
| `p` | 累积分布函数 CDF，$P(X\le k)$ | `ppois(800,mu)`、`pbinom(1,20,p)` |
| `q` | 分位数函数（CDF 的逆） | `qnorm(0.975)` |
| `r` | 随机数生成 | `rpois(n, lambda)` |
| `lower.tail = FALSE` | 直接算**上尾** $P(X>k)$，避免 $1-P$ 的精度损失 | `ppois(800, mu, lower.tail=FALSE)` |

---

## 10. 本讲五条核心直觉（考前回顾用）

**直觉一：直方图是"经验版的 PDF"，它决定我们挑哪个分布族。** 柱子的面积对应数据比例——这正是 PDF"曲线下面积等于概率"的离散化。所以看到直方图右偏，就该想到 Poisson/Exponential 这类右偏分布；看到钟形，就想到正态。**"选分布族"靠形状，"定参数"靠 MLE，这是一条完整的流水线。**

**直觉二：似然函数把"概率"的角色对调了一下，就产生了统计推断。** 概率论里 $f(x;\theta)$ 是"固定 $\theta$、问 $x$ 的概率"；统计学里 $L(\theta)$ 是"固定看得到的 $x$、问哪个 $\theta$ 更相容"。**数据是已定的事实，参数才是要找的东西**——这个视角的翻转，是整个统计学的起点。

**直觉三：MLE = "挑一个让观测到的数据看起来最不意外的参数"。** 而第 8 节的定理给了它底气：**大样本时，似然的峰几乎总在真值头上**。但代价是——它只保证渐近正确，**不保证有限样本下无偏**（Uniform 例子就是铁证：$E[\hat\theta] = \frac{n}{n+1}\theta$，系统性低估；Poisson 例题里 $-\ell''=n/\bar x$ 也提醒我们"凹"只是局部保证最大值，不代表无偏）。

**直觉四（板书给出的、也是本讲最漂亮的一点）：第 4 节那些"凭直觉凑出来"的估计量，全都是 MLE。** `mu = sum(Positive) = 788` 是 Poisson 全年速率 $n\lambda$ 的 MLE，`p = 788/16000` 是 Bernoulli 的 MLE $\bar x$，连 `summary()` 输出里那一格不起眼的 `Mean = 2.201` 也是日感染率 $\lambda$ 的 MLE。**这说明直觉在简单问题里确实能猜对；但理论的价值在于，它能告诉你什么时候直觉会错**——一旦踩到 Uniform 那种"支撑集含参数"或"参数是多维"的情形，凭感觉凑就完全失灵了。**直觉负责快，理论负责对。**

**直觉五（板书预告的下一讲主线）：判一个估计量好不好，看四个量，分两个层次。** **有限样本**层次看三个——**Bias**（平均准不准，$E\hat\theta-\theta$）、**Var**（抖不抖，$E[(\hat\theta-E\hat\theta)^2]$）、**MSE**（把前两者合成一个数，$\text{MSE}=\text{Var}+\text{Bias}^2$）；**渐近**层次看一个——**Consistency**（样本多了会不会变准，$\hat\theta\xrightarrow{P}\theta$）。**最容易搞错的不是公式，而是它们之间的关系**：无偏不等于相合（$\hat\theta=X_1$ 无偏但方差永不缩小），相合也不等于无偏（$X_{(n)}$ 有偏但相合）；而 MSE 分解告诉我们**"稍微有偏 + 方差很小"可能打赢"完全无偏 + 方差很大"**——这就是正则化类方法存在的理由。

---

## 11. 中英术语对照

| 中文 | English |
| --- | --- |
| 数据可视化 / 探索性数据分析 | data visualization / exploratory data analysis (EDA) |
| 直方图 / 组距 / 箱（区间） | histogram / bin width / bin |
| 相对频数 / 密度 | relative frequency / density |
| 过拟合 / 过度平滑 | overfitting / over-smoothing |
| 箱线图 / 箱须图 | boxplot / box-and-whisker diagram |
| 五数概括 | five-number summary |
| 最小值 / 第一四分位数 / 中位数 / 第三四分位数 / 最大值 | minimum / first quartile $Q_1$ / median / third quartile $Q_3$ / maximum |
| 四分位距 | interquartile range (IQR) |
| 内栅栏 / 外栅栏 | inner fence / outer fence |
| 须 | whisker |
| 可疑离群点 / 离群点 | suspected outlier / outlier |
| 偏态 / 左偏 / 右偏 | skewness / left-skewed (negatively skewed) / right-skewed (positively skewed) |
| 双峰的 | bimodal |
| 标准差 / 变异系数 | standard deviation / coefficient of variation (CV) |
| 总体 / 样本 / 样本量 | population / sample / sample size |
| 独立同分布 | independent and identically distributed (i.i.d.) |
| 参数 / 参数空间 | parameter / parameter space |
| 估计量 / 估计值 / 点估计量 | estimator / estimate / point estimator |
| 区间估计 | interval estimator |
| 偏差 / 无偏估计量 | bias / unbiased estimator |
| 均方误差 / 偏差–方差分解 | mean squared error (MSE) / bias–variance decomposition |
| 相合性 / 相合估计量 | consistency / consistent estimator |
| 依概率收敛 | convergence in probability |
| 精度 / 准确度 | precision / accuracy |
| 收缩 / 正则化 | shrinkage / regularization |
| 似然函数 / 对数似然函数 | likelihood function / log-likelihood function |
| 得分函数 / 似然方程 | score function / likelihood equation |
| 驻点 / 二阶条件 | stationary point / second-order condition |
| 海森矩阵 / 负定 | Hessian matrix / negative definite |
| 最大似然估计 | maximum likelihood estimator (MLE) |
| 矩估计量 / 矩估计法 | Method of Moments estimator / Method of Moments |
| 充分统计量 | sufficient statistic |
| Fisher 信息量 | Fisher information |
| 指数族 | exponential family |
| 正则条件 | regularity conditions |
| 可识别性 | identifiability |
| 支撑集 / 共同支撑集 | support / common support |
| 指示函数 | indicator function |
| 内点 | interior point |
| 相合性 / 渐近无偏 | consistency / asymptotically unbiased |
| 顺序统计量 | order statistic |
| 尺度参数 / 速率参数 | scale parameter / rate parameter |
| 不变性（MLE） | invariance property |
| 定义为（记号 $\triangleq$） | is defined as |
| 泊松分布 / 二项分布 / 几何分布 / 均匀分布 / 指数分布 | Poisson / Binomial / Geometric / Uniform / Exponential distribution |
| 累积分布函数 | cumulative distribution function (CDF) |
| 上尾概率 | upper-tail probability |

---

## 附：本笔记相对讲义的补充与说明（诚实备注）

### 材料来源

本笔记由**三部分材料**合成：

1. 课件 `Lecture2 - Parameter Estimation I.pdf`（18 页 Slides）；
2. 配套 R 实践讲义 `Lec2_Covid.pdf`（7 页）与数据集 `UM_C19_2021.csv`（1063 行）；
3. **本讲课堂板书**（内容已提炼并入 2.4、6.3、7.2、7.3.1、7.4.1、7.6.1、7.7、7.8 各节，未收录板书原图）。

**本讲的材料只有讲义与板书**，因此笔记**不包含任何超出这两份材料的内容**。板书内容我按原样转写为 LaTeX，含混不清之处在对应位置作了标注，不作臆测。讲义第 4、5 页的图（蜂蜡熔点直方图、箱线图示意图）与 `Lec2_Covid.pdf` 第 4、5 页的 R 图形，我已将页面渲染为图片逐一读取以确认细节。

**课堂板书相对讲义的增量（已提炼进正文的位置）**：

| 板书内容 | 性质 | 笔记小节 |
| --- | --- | --- |
| Boxplot：五数概括位置、$\mathrm{IQR}$、须的 $\arg\min$ 严格定义、两级离群点阈值 | 把讲义绕口的表述写成精确式子 | 2.4 |
| 似然函数的两分支正式写法（PMF / PDF）与 $\overset{iid}{=}$ | 讲义只有合写版，未强调两种情形之分 | 6.3 |
| MLE 计算套路 ①②③ 框、$\ln L\triangleq\ell$、多参数的海森推广 | **讲义完全没有**，是一套可复用的求解配方 | 7.2 |
| Bernoulli $(p)$ 用 $\bar x$ 压缩的写法 + "score function" 命名 | 等价改写 + 术语落点 | 7.3.1 |
| 圈出的 $\lambda e^{-\lambda x}$ | 指数分布的速率参数化；疑为 Poisson 到达间隔的注记 | 7.4.1 |
| **Uniform $[0,\theta]$ 的指示函数（indicator）写法** | **讲义全程未用指示函数**；$n$ 个约束塌缩为 $\min/\max$ 两个 | 7.6.1 |
| **Poisson $(\lambda)$ 例题的完整 MLE 推导** | **讲义没有这道题**；它证明了第 4 节的直觉估计就是 MLE | 7.7 |
| **直方图柱高的两个精确公式**（$\frac{n_j}{n}$、$\frac{n_j}{w_j n}$）与归一化恒等式 $\sum_j w_j\frac{n_j}{w_j n}=1$ | 讲义只有文字描述"相对频数或密度"，未落成公式 | 1.1 |
| **估计量的评价标准**：Bias、Var、MSE（含偏差–方差分解）、Consistency | 板书写在 `Criteria` 一行下；**讲义完全没有** | 5.4 |

> **课堂推进顺序**：从板书前后状态（较早时板上是 Bernoulli 那一块，较晚时已被擦掉换成 Uniform，而 ①②③ 计算框与 Poisson 结果一直保留）可推，课堂例题顺序为 **Poisson → Bernoulli $(p)$ → Uniform $[0,\theta]$**。**Uniform 收尾**这一点与讲义第 13–16 页的排列一致，差别在于**板书比讲义多做了一道 Poisson 例题**（讲义第 13 页直接从 Bernoulli 开始）。

### 课堂抄录笔记的合并（2026-09-15 追加）

用户提供了一份课上抄录的完整笔记（覆盖直方图公式、箱线图与离群点阈值、EDA 两个问题、参数估计框架、MLE 三步法与三道例题），本次已并入正文，并**逐行核对、修正了抄录中的笔误**。核对结果如下：

**（1）与笔记完全一致、无需改动的部分**

- 直方图：$\text{bin }j = \frac{n_j}{n}$、$\text{Density} = \frac{n_j}{w_j n}$、$\sum_{j=1}^{k} w_j\frac{n_j}{w_j n} = 1$ ✅
- 箱线图：$\min, Q_1(\frac14), Q_2(\text{median}), Q_3(\frac34), \max$、$\mathrm{IQR}=Q_3-Q_1$、$\text{lower whisker}=Q_1-1.5\,\mathrm{IQR}$ ✅
- 两级离群点阈值（$1.5\,\mathrm{IQR}$ 与 $3\,\mathrm{IQR}$）✅
- EDA 两个问题（Poisson 预测下一年发生数、Binomial 预测统计系 20 人感染数）✅
- MLE 三步法与 Poisson 例题的 $L(\lambda)$、$\ell(\lambda)$ ✅

**（2）抄录中的笔误（已在正文对应位置标注并修正）**

| 位置 | 抄录原文 | 应为 | 性质 |
| --- | --- | --- | --- |
| §5.4.2 方差 | $\operatorname{Var}(\theta) = E(\hat\theta - E\hat\theta)$ | $\operatorname{Var}(\hat\theta)=E[(\hat\theta-E\hat\theta)^2]$ | ① 左边应为 $\hat\theta$（评价的是估计量）；② **漏了平方**——不平方则恒为0 |
| §5.4.3 MSE | $\operatorname{MSE}(\theta) = E(\theta-\theta)^2$ | $\operatorname{MSE}(\hat\theta)=E[(\hat\theta-\theta)^2]$ | 左边与括号内第一个 $\theta$ 都应为 $\hat\theta$ |
| §5.4.4 相合性 | `∀ ≤ 20`、`∀ ≥ 30`、`P{θ²-θ)²` | $\forall\varepsilon>0,\ \lim_{n\to\infty}\Pr(\lvert\hat\theta-\theta\rvert>\varepsilon)=0$ | 手写体辨认错误（$\varepsilon$ 与数字、$\hat\theta$ 与 $\theta$ 易混）；已按标准定义还原 |
| §7.7 似然 | $\prod P(x_i = x_i\,i\lambda)$ | $\prod_{i=1}^{n}P(X_i=x_i;\lambda)$ | 分号 `;` 被输入为 `i`；参数与观测值用**分号**而非竖线 |
| §7.7 似然 | $\lambda^{\sum^{n}_{i=1}}$ | $\lambda^{\sum_{i=1}^{n}x_i}$ | 漏了被求和的 $x_i$ |
| §7.7 似然 | $e^-n\lambda$ | $e^{-n\lambda}$ | 负号范围需括住 $n\lambda$ |
| §7.6.1 指示函数 | $\mathbb{1}\{x\in[0,\theta)\}$ | $[0,\theta]$ 或 $[0,\theta)$ 皆可 | 端点开闭在本题**完全等价**（单点概率为 0）；已加说明 |

**（3）最重要的发现：θ̂ 前一处"减号"被证实为板书笔误**

抄录笔记里 Bernoulli 的对数似然写作

$$u(p) = n\bar x\ln p - n(1-\bar x)\ln(1-p)$$

**确认是减号**。这**证实了正文 7.3.1 节原本只是"推断"的结论**：该减号与同一块板上紧接着的一阶导 $\frac{n\bar x}{p} - \frac{n(1-\bar x)}{1-p}$、二阶导 $-\frac{n\bar x}{p^2} - \frac{n(1-\bar x)}{(1-p)^2}$ **无法同时成立**。验算很简单：若为减号，则 $\ell'(p) = \frac{n\bar x}{p} + \frac{n(1-\bar x)}{1-p} > 0$ 恒成立、**永远解不出 $\hat p=\bar x$**。故本笔记按**加号版本（数学正确版）**记录，并在 7.3.1 节新增了完整的交叉验证说明。**这是一处值得警惕的"抄板书要当场验算"的实例。**

**以下数值均已用 Python 独立复算并与讲义核对一致**：三组人群 `summary()` 的全部描述统计量（均值、中位数、四分位数、最值，其中四分位数与 R 的 type 7 插值定义一致）、`sd()` 的三个标准差（$0.0177996$ / $0.0464122$ / $0.1942217$）、教职工全年阳性总数 $\sum = 788$、教职工组均值 $\bar x = 788/358 = 2.2011$（与 `summary()` 输出的 `Mean = 2.201` 吻合）、$p = 788/16000 = 0.04925$、Poisson 的 $P(X\le400) = 7.7015\times10^{-53}$ 与 $P(X\le800) = 0.6736617$、Binomial 的 $P(X=0) = 0.3641889$、$P(X=1) = 0.3773085$、$P(X\ge2) = 0.2585026$。

**以下内容属于"讲义未给出、我补充"的部分，供参考，考试请以讲义与教师要求为准**：

- **板书例题 Poisson $(\lambda)$ 的 ①②③ 完整四步**（6.3、7.2、7.7 节）：这一例题**讲义里没有**，完全来自板书。我按板书的推导顺序补全了每一步的理由，并额外给出了"$\sum x_i = n\bar x$"的改写、常数项 $\log(\prod x_i!)$ 可丢弃的理由、以及 $\ell''$ 的完整计算。
- **1.1 节直方图的两个精确公式与归一化恒等式**（$\frac{n_j}{n}$、$\frac{n_j}{w_j n}$、$\sum_j w_j\frac{n_j}{w_j n}=1$）：公式本身来自课堂抄录，但"**相对频数只在等宽时面积和为 1、不等宽时必须用密度**"这一段解释、以及"为什么软件默认画密度"的说明是我补充的（讲义只有"相对频数或密度"一句文字描述）。
- **5.4 节估计量评价标准的详细展开**（Bias / Var / MSE 的偏差–方差分解完整推导 / Consistency）：板书写了 `Criteria: Unbiased, Consistent` 一行，并给出 $\text{Bias}=E(\hat\theta)-\theta$、$\operatorname{MSE}=E[(\hat\theta-\theta)^2]=\operatorname{Var}+\text{Bias}^2$ 等式子。**三个量在板书上只有式子，没有解释**——「打靶类比」、「无偏 ≠ 每次都对」、MSE 分解的两步推导、「无偏 $\not\Rightarrow$ 相合 / 相合 $\not\Rightarrow$ 无偏」的两个反例（$\hat\theta=X_1$ 与 $X_{(n)}$）、以及"渐近无偏 + 方差→0 ⇒ 相合"这一充分条件，均为我补充。**本讲只列名，正式比较是第 3 讲的内容。**
- **7.3.1 节的交叉验证**：抄录笔记证实板书 Bernoulli 对数似然处确为减号，我据此补出了"减号会导致 $\ell'>0$ 恒成立、解不出 $\hat p$"的完整反证，并确认按加号版本记录。
- **7.6.1 节关于区间端点开闭等价的说明**（$[0,\theta]$ vs $[0,\theta)$）：两条理由（单点概率为0、结论 $\hat\theta=\max x_i$ 不变）是我补充的。
- **7.7.1 节"闭合逻辑循环"的对应关系表**（第 4 节三个估计量 ↔ 三个 MLE）：这是**我从板书例题与第 4 节内容推导出的联系**，讲义与板书都未明确指出。其中"独立 Poisson 变量之和仍为 Poisson、参数相加"这一性质来自第 1 讲的 MGF 方法，用于把"日感染率 $\hat\lambda=\bar x$"与"全年总数 $=n\hat\lambda=788$"打通。
- **7.8 节末尾关于矩估计量（MoM）的对照**（Uniform 的 MoM 给 $2\bar x$、与 MLE 的 $X_{(n)}$ 不同）：这是我补充的，用来防止"理论均值 = 样本均值"被误当成 MLE 的普遍定义。正式内容在下一讲。
- **2.4 节对板书 $\arg\min$ 定义的逐字解读**，包括"严格不等号 $x > Q_1-1.5\,\mathrm{IQR}$ 意味着恰恰落在栅栏线上的点不算进须里"这一细节，以及"板书把两级阈值都叫 potential outliers 是更保守也更贴合统计学立场的措辞（离群 ≠ 错误数据）"这一评价。
- **7.2 节对板书第③步写成 $-\ell''>0$ 的用意分析**（与 Fisher 信息量的定义 $-E[\ell'']$ 形式一致；多参数时推广为海森矩阵负定）。板书只给了式子，未解释为何这样写。
- **6.3 节对 $\overset{iid}{=}$ 符号的解读**（"i" 提供联合 = 边缘之积、"d" 提供共用同一参数，所以那个漂亮连乘是 i.i.d. 假设"买"来的）。
- **7.3.1 节关于"充分统计量"的点注**（$\ell$ 只通过 $\bar x$ 依赖全部数据）：板书未提这个概念，属预防性补充。
- **7.3.1 节末尾关于板书 $\ell(p)$ 符号歧义的说明**：板书上 $\ell(p)$ 第二项与同一块板上紧接着的一阶导 $\frac{n\bar x}{p} - \frac{n(1-\bar x)}{1-p}$、二阶导 $-\frac{n\bar x}{p^2} - \frac{n(1-\bar x)}{(1-p)^2}$ **不能同时成立**——后两行只与"加号"版本自洽（一阶导里的负号来自 $\log(1-p)$ 的链式法则）。**本笔记按数学自洽的加号版本记录**，即 $\ell(p) = n\bar x\log p + n(1-\bar x)\log(1-p)$，并把判断理由写在正文里。第二项括号同理按 $(1-p)$ 而非 $(1+p)$。**→ 2026-09-15 已由课堂抄录笔记证实板书确为减号，属笔误；完整验算见该节新增的交叉验证块。**
- 组距自动选择的两条具体规则（Sturges、Freedman–Diaconis）及其公式，以及 Python/NumPy 的对应实现方式。
- 内外栅栏系数 $1.5$ 与 $3$ 的来源直觉（正态下约千分之几的概率），以及 **R 的 `boxplot()` 只用单层 $1.5\,\mathrm{IQR}$ 门槛、不区分"可疑/确定"离群点**这一软件差异。
- 3.3 节对三组描述统计量的解读（均值 > 中位数 → 右偏；中位数低而最大值极高 → 偶发爆发模式），以及 3.4 节用**变异系数 CV** 替代绝对标准差做跨组比较的算法与结论（$CV_{fs}\approx1.29$、$CV_{ns}\approx1.42$、$CV_{rs}\approx2.27$，住宿学生相对波动最大）。讲义只给了代码和输出，未做解读。
- 3.6 节对两张箱线图（`Lec2_Covid.pdf` 第 5 页）的读图解读。**另需留意**：该页代码的 `ylab` 写的是 `"Total Tests"`，但纵轴实际绘制的是 `covid$Total`（当日**检测总数** = 阳性 + 阴性），并非"阳性总数"。
- 4.1 节关于 `ppois(800,mu)-ppois(400,mu)` 输出与 `ppois(800,mu)` **完全相同**的解释：这不是讲义算错，而是 $P(X\le400)=7.7\times10^{-53}$ 相对于 $0.6736617$ 小到在双精度浮点减法中被完全吞掉（灾难性抵消）。
- 4.2 节中把"16000 人出 788 例"直接当作"每人感染概率 $=788/16000$"所隐含的假设（每人至多感染一次、人与人之间独立），以及"独立性在传染病场景下不成立"这一提醒。同时 4.1 与 4.2 两节用了**同一个 788**，但两个模型的假设并不完全兼容（时间速率 vs 个体独立机会）。
- 7.2 节的三步法之后补充的**第四步"验证 $\ell''<0$"**：讲义四道例题都只给了 $\hat\theta$，未做二阶条件检验。我在 7.3–7.5 各例中补了完整验证。
- 7.3 节 Bernoulli 的**边界情形**（全部 $x_i=0$ 或全部 $=1$，最大值在 $p=0$ 或 $p=1$ 取得）——这解释了为什么 $\Omega$ 写成闭区间。
- 7.4 节的**指数分布两种参数化**（尺度 vs 速率）的对照，以及 **MLE 的不变性（invariance property）**（$\hat\lambda = 1/\bar X$）。
- 7.5 节几何分布"试验次数"与"失败次数"两种定义的区别（$E[X]=1/p$ vs $(1-p)/p$）。
- **7.6.1 指示函数（indicator function）写法**（板书新引入的记号，讲义全程未用）：我按板书转写了 $f$ 与 $L$ 的指示函数形式，并补充了三条解读——① 指示函数的定义与"它就是把分段函数压进一个公式"；② **乘积 = 交集的规则** $\prod_i\mathbb{1}\{A_i\}=\mathbb{1}\{\bigcap_i A_i\}$，以及由它导出的"$n$ 个约束塌缩成 $\min$ 与 $\max$ 两个"这一步（我认为这是整块板书最有含金量的一步）；③ **两条约束地位不同**：$\min_i x_i \ge 0$ **不含 $\theta$**、是对数据的合法性检查（若某个观测为负则 $L\equiv 0$、MLE 不存在），$\max_i x_i \le \theta$ 才是约束 $\theta$ 的那一条。此外我还补了"取最小可行值"的坡–墙类比，以及"光滑部分 × 指示条件"这一处理支撑集依赖参数问题的通用套路。
- **7.4.1 板书圈出的 $\lambda e^{-\lambda x}$**：我给出了两种读法并标注了把握程度——（把握较大）它就是指数分布的速率参数化形式，与 7.4 节的尺度参数化 $\frac{1}{\theta}e^{-x/\theta}$ 同族（$\lambda = 1/\theta$），照应 MLE 的不变性；（**我的推断，建议对照课堂确认**）更可能是与紧邻的 Poisson 例题配套的注记，即 **Poisson 过程的到达间隔服从速率 $\lambda$ 的指数分布**。后者我给出了完整推导（$P(T>t) = P(\text{Poisson}(\lambda t)=0) = e^{-\lambda t}$，求导得 $\lambda e^{-\lambda t}$），可视为对"板书为何把它圈在 Poisson 旁边"的一个侧面印证。**板书只写了式子、没有文字说明，这段读法是我的推断，不是板书原话。**
- 7.6 节 Uniform 例中 **$\hat\theta = X_{(n)}$ 是有偏的**这一结论及其证明要点（$E[X_{(n)}] = \frac{n}{n+1}\theta$，故系统性低估、渐近无偏）。这是**下一讲（无偏性/有效性）的引子**，讲义未提。
- 7.6 节关于"为什么求导法失效"的三层解释（最优解落在可行域边界、$L$ 在 $\theta=\max x_i$ 处不可导、违反正则条件 (R2)）。
- 8.1 节对 (R1)–(R3) 三条条件的**反例与作用说明**（例如 $\theta$ 与 $-\theta$ 不可识别需限制参数空间）。
- 8.2 节对定理的三个 caveat（渐近而非有限样本、概率性而非必然、讲义明说不考）——**讲义原文已明确标注 "This theorem is not required in this course"**，故只需理解其含义，无需掌握证明。
- 讲义第 2 页将 "Exploratory Data Analysis" 写作 **Explanatory** data analysis（标准术语为 Exploratory）；第 1 页授课教师名写作 **Ka Wai Tseng**，而第 1 讲笔记中记为 Ka Wai **Tsang**。
- 数据集的一个事实性观察：讲义称数据覆盖 2020/8/16–2021/8/15（一年），但 CSV 实际共 1063 条记录，三组分别为 358 / 361 / 344 天，**并非每组都有 365 天记录**。这意味着 4.1 节用 $\sum\text{Positive} = 788$ 作为"一年发生数"时，隐含地把缺失日期当作零处理。
- 第 9 节速查表中的 R 函数 `d/p/q/r` 命名规律、以及 `lower.tail = FALSE` 用于规避**灾难性抵消**的数值理由，讲义只给了用法未给解释。